import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ignorePatterns: [
      "**/*.gen.ts",
      "*.md",
      "api/**",
      "docs/**",
      "internal/**",
      "packaging/**",
      "skills/**",
      "pnpm-lock.yaml",
    ],
  },
  lint: {
    categories: { correctness: "error" },
    ignorePatterns: ["**/dist/**", "**/*.gen.ts"],
    plugins: ["typescript", "unicorn", "oxc", "import", "vitest"],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: {
      curly: ["error", "all"],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "import/first": "error",
      "import/no-duplicates": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
      "import/no-nodejs-modules": "error",
      "import/no-self-import": "error",
      "no-implicit-coercion": "error",
      "no-lonely-if": "error",
      "no-restricted-globals": [
        "error",
        "process",
        "Buffer",
        "global",
        "__dirname",
        "__filename",
        "require",
        "module",
        "exports",
        "setImmediate",
        "clearImmediate",
      ],
      "no-unneeded-ternary": "error",
      "object-shorthand": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-object-spread": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "unicorn/prefer-node-protocol": "error",
    },
    overrides: [
      {
        files: ["**/vite.config.ts"],
        rules: { "import/no-nodejs-modules": "off", "no-restricted-globals": "off" },
      },
    ],
    options: {
      denyWarnings: true,
      reportUnusedDisableDirectives: "error",
      typeAware: true,
      typeCheck: true,
    },
  },
});
