// Generates Effect Schemas and an HttpClient for api/openapi.yaml.
// Run through scripts/generate-openapi.sh.
import * as NodeFileSystem from "@effect/platform-node/NodeFileSystem";
import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as OpenApiGenerator from "@effect/openapi-generator/OpenApiGenerator";
import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import type * as JsonSchema from "effect/JsonSchema";
import * as Yaml from "effect/unstable/encoding/Yaml";
import type * as OpenApi from "effect/unstable/httpapi/OpenApi";

const spec = new URL("../../../api/openapi.yaml", import.meta.url);
const output = new URL("../src/api.gen.ts", import.meta.url);

// The generator emits shared helpers that go unused for some specs, which the strict
// compiler options of the consuming packages reject.
const header = `// Generated by packages/api-schema/scripts/generate.ts from api/openapi.yaml. Do not edit.
// @ts-nocheck
`;

const SENSITIVE = "SensitiveString";

function normalize(schema: JsonSchema.JsonSchema): JsonSchema.JsonSchema {
  if (schema["x-sensitive"] === true) {
    const { "x-sensitive": _, type: __, ...annotations } = schema;
    return { $ref: `#/$defs/${SENSITIVE}`, ...annotations };
  }
  const out = { ...schema };
  // The generator only accepts patterns in the form RegExp#source prints them, so `/`
  // must be escaped. The escaped form matches the same strings.
  if (typeof out.pattern === "string") out.pattern = new RegExp(out.pattern).source;
  // Objects without additionalProperties would otherwise gain a JSON index signature.
  // Decoding still ignores unknown properties, so newer servers remain compatible.
  if (out.properties !== undefined && out.additionalProperties === undefined) {
    out.additionalProperties = false;
  }
  return out;
}

function replaceOnce(source: string, search: string, replacement: string): string {
  if (source.split(search).length !== 2) {
    throw new Error(`expected exactly one ${JSON.stringify(search)} in the generated source`);
  }
  return source.replace(search, replacement);
}

// The generator cannot emit Redacted, so the shared sensitive string is rewritten after
// generation. Payloads are sent as their Encoded type, which stays a plain string.
function redactSensitive(source: string): string {
  const withType = replaceOnce(
    source,
    `export type ${SENSITIVE} = string\n`,
    `export type ${SENSITIVE} = Redacted.Redacted<string>\n`,
  );
  const withSchema = replaceOnce(
    withType,
    `export const ${SENSITIVE} = Schema.String.annotate({ "identifier": "${SENSITIVE}" })\n`,
    `export const ${SENSITIVE} = Schema.RedactedFromValue(Schema.String).annotate({ "identifier": "${SENSITIVE}" })\n`,
  );
  const withImport = replaceOnce(
    withSchema,
    `import * as Schema from "effect/Schema"\n`,
    `import * as Redacted from "effect/Redacted"\nimport * as Schema from "effect/Schema"\n`,
  );
  return withImport.replaceAll(`Schema.Codec<${SENSITIVE}>`, `Schema.Codec<${SENSITIVE}, string>`);
}

const program = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const generator = yield* OpenApiGenerator.OpenApiGenerator;

  const warnings: OpenApiGenerator.OpenApiGeneratorWarning[] = [];
  const parsed = Yaml.parse(yield* fs.readFileString(spec.pathname)) as OpenApi.OpenAPISpec;
  const document: OpenApi.OpenAPISpec = {
    ...parsed,
    components: {
      ...parsed.components,
      schemas: { ...parsed.components.schemas, [SENSITIVE]: { type: "string" } },
    },
  };
  const generated = yield* generator.generate(document, {
    name: "ApertureApi",
    format: "httpclient",
    onEnter: normalize,
    onWarning: (warning) => warnings.push(warning),
  });
  for (const warning of warnings) {
    yield* Console.warn(`${warning.code} ${warning.operationId ?? ""}: ${warning.message}`);
  }
  const source = redactSensitive(generated);
  yield* fs.writeFileString(output.pathname, `${header}${source}\n`);
});

program.pipe(
  Effect.provide([OpenApiGenerator.layerTransformerSchema, NodeFileSystem.layer]),
  NodeRuntime.runMain,
);
