// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Time-ordered UUID version 7 generated by Aperture.
 */
export const zUuiDv7 = z.uuid();

/**
 * Authorization boundary. `system_admin` principals may administer the deployment and select tenants. `tenant` principals act within one effective tenant.
 *
 */
export const zAuthorityType = z.enum(['system_admin', 'tenant']);

/**
 * Stable category of the authenticated or audited actor.
 */
export const zPrincipalType = z.enum([
    'api_token',
    'user',
    'system'
]);

/**
 * Permission granted to a principal. `system:admin` implies every scope. Tenant credentials and memberships cannot receive `system:admin` or `tenants:write`.
 *
 */
export const zScope = z.enum([
    'system:admin',
    'sessions:read',
    'sessions:write',
    'snapshots:read',
    'snapshots:write',
    'tenant:write',
    'tenants:write'
]);

/**
 * Scope allowed on a tenant-bound API token.
 */
export const zTenantScope = z.enum([
    'sessions:read',
    'sessions:write',
    'snapshots:read',
    'snapshots:write',
    'tenant:write'
]);

/**
 * Whether a tenant API token can access every tenant resource or only explicit grants.
 */
export const zResourceMode = z.enum(['all', 'allowlist']).default('all');

/**
 * Tenant resource category accepted by API token allowlists.
 */
export const zResourceType = z.enum(['session', 'snapshot']);

/**
 * Access to one existing tenant session or snapshot by its stable UUIDv7 identifier.
 */
export const zResourceGrant = z.object({
    resourceType: zResourceType,
    resourceId: zUuiDv7
});

/**
 * Session lifecycle state:
 *
 * - `creating`: browser startup is in progress; the CDP endpoint does not answer yet.
 * - `running`: browser and routing are available and the CDP endpoint answers.
 * - `suspended`: browser is intentionally stopped while retained state remains available.
 * - `deleted`: session is soft-deleted and may be reopened while retained.
 * - `expired`: retention elapsed and the session can no longer be used.
 * - `failed`: startup or reopen failed; retained state may still be reopenable.
 *
 */
export const zSessionStatus = z.enum([
    'creating',
    'running',
    'suspended',
    'deleted',
    'expired',
    'failed'
]);

/**
 * Arbitrary string key-value metadata. Tag-writing operations additionally reject blank keys and blank values.
 */
export const zStringMap = z.record(z.string(), z.string());

/**
 * Cursor pagination metadata for a newest-first result page.
 */
export const zPageMeta = z.object({
    limit: z.int().gte(1).lte(100),
    nextCursor: z.string().optional(),
    hasMore: z.boolean()
});

/**
 * Stable machine-readable error code.
 */
export const zErrorCode = z.enum([
    'authentication_required',
    'invalid_authentication_token',
    'authentication_token_expired',
    'authentication_token_revoked',
    'insufficient_scope',
    'resource_access_denied',
    'tenant_selection_not_permitted',
    'tenant_selection_required',
    'tenant_not_found',
    'token_not_found',
    'tenant_deactivated',
    'token_name_conflict',
    'token_delegation_exceeded',
    'user_not_found',
    'user_disabled',
    'user_email_conflict',
    'user_invitation_unavailable',
    'membership_not_found',
    'oidc_provider_not_found',
    'oidc_flow_invalid',
    'oidc_authentication_failed',
    'identity_not_provisioned',
    'validation_failed',
    'invalid_request_body',
    'session_not_found',
    'session_expired',
    'base_snapshot_not_found',
    'base_snapshot_deleted',
    'session_not_reopenable',
    'session_overlay_missing',
    'session_invalid_state',
    'session_not_running',
    'recording_not_found',
    'recording_invalid_state',
    'session_file_not_found',
    'browser_start_failed',
    'browser_initialization_failed',
    'snapshot_not_found',
    'snapshot_name_conflict',
    'snapshot_deleted',
    'snapshot_not_deleted',
    'session_not_promotable',
    'promotion_conflict',
    'browser_channels_unavailable',
    'event_service_unavailable',
    'session_service_unavailable',
    'promotion_service_unavailable',
    'snapshot_service_unavailable',
    'overlay_mount_failed',
    'browser_control_failed',
    'internal_error'
]);

/**
 * Stable machine-readable error code with a human-readable explanation.
 */
export const zErrorDetail = z.object({
    code: z.string(),
    message: z.string()
});

/**
 * Standard error envelope returned by REST API operations.
 */
export const zError = z.object({
    error: zErrorDetail
});

/**
 * Local deployment health and blue-green role information.
 */
export const zHealth = z.object({
    status: z.enum(['ok']),
    color: z.enum(['blue', 'green']),
    role: z.enum(['active', 'inactive']),
    version: z.string(),
    activeColor: z.enum(['blue', 'green'])
});

/**
 * Tenant fields accepted by create and update operations.
 */
export const zTenantInput = z.object({
    displayName: z.string().min(1).regex(/.*\S.*/)
});

/**
 * Tenant account. Deletion is a reversible soft deactivation.
 */
export const zTenant = z.object({
    id: zUuiDv7,
    displayName: z.string(),
    createdAt: z.iso.datetime(),
    deletedAt: z.iso.datetime().nullish()
});

/**
 * Cursor-paginated tenants.
 */
export const zTenantPage = z.object({
    data: z.array(zTenant),
    meta: zPageMeta
});

export const zUserInput = z.object({
    email: z.email().nullish(),
    displayName: z.string().min(1).regex(/.*\S.*/),
    isSystemAdmin: z.boolean()
});

export const zUser = z.object({
    id: zUuiDv7,
    email: z.email().nullish(),
    displayName: z.string(),
    isSystemAdmin: z.boolean(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    disabledAt: z.iso.datetime().nullish(),
    passwordSetupStatus: z.enum([
        'available',
        'configured',
        'email_required',
        'user_disabled',
        'login_disabled'
    ]).optional()
});

/**
 * One-time account setup secret returned only when created.
 */
export const zUserInvitation = z.object({
    token: z.string(),
    expiresAt: z.iso.datetime()
});

export const zUserPage = z.object({
    data: z.array(zUser),
    meta: zPageMeta
});

export const zTenantMembershipInput = z.object({
    scopes: z.array(zTenantScope).min(1)
});

export const zTenantMembership = z.object({
    tenantId: zUuiDv7,
    userId: zUuiDv7,
    scopes: z.array(zTenantScope).min(1),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zAuditEvent = z.object({
    id: zUuiDv7,
    actorType: zPrincipalType,
    actorId: z.string().nullish(),
    tenantId: zUuiDv7.nullish(),
    action: z.string(),
    resourceType: z.string(),
    resourceId: z.string().nullish(),
    data: z.record(z.string(), z.unknown()),
    createdAt: z.iso.datetime()
});

export const zAuditEventPage = z.object({
    data: z.array(zAuditEvent),
    meta: zPageMeta
});

/**
 * Authenticated subject identity and authorization context.
 */
export const zPrincipal = z.object({
    type: zPrincipalType,
    id: z.string(),
    authMethod: z.enum([
        'api_token',
        'oidc',
        'passkey',
        'password'
    ]),
    tokenId: zUuiDv7.nullable(),
    userId: zUuiDv7.nullish(),
    name: z.string(),
    authorityType: zAuthorityType,
    tenantId: zUuiDv7.nullish(),
    scopes: z.array(zScope),
    resourceMode: zResourceMode,
    resourceGrants: z.array(zResourceGrant)
});

/**
 * Current principal and its effective tenant selection.
 */
export const zAuthMe = z.object({
    principal: zPrincipal,
    selectedTenant: zTenant.nullable(),
    availableTenants: z.array(zTenant)
});

/**
 * Browser runtime selectable when creating a session.
 */
export const zBrowserChannel = z.object({
    name: z.string()
});

/**
 * Browser channels enabled on this deployment.
 */
export const zBrowserChannels = z.object({
    channels: z.array(zBrowserChannel)
});

/**
 * API token metadata. The raw bearer secret is never included in this schema.
 */
export const zToken = z.object({
    id: zUuiDv7,
    authorityType: zAuthorityType,
    tenantId: zUuiDv7.nullish(),
    name: z.string(),
    scopes: z.array(zScope).min(1),
    createdAt: z.iso.datetime(),
    createdByType: zPrincipalType,
    createdById: zUuiDv7.nullable(),
    parentTokenId: zUuiDv7.nullable(),
    resourceMode: zResourceMode,
    resourceGrants: z.array(zResourceGrant),
    expiresAt: z.iso.datetime().nullish(),
    revokedAt: z.iso.datetime().nullish()
});

/**
 * Token definition accepted by the system administrator token endpoint.
 */
export const zCreateAdminTokenInput = z.union([
    z.object({
        name: z.string().min(1).regex(/.*\S.*/),
        authorityType: z.enum(['system_admin']),
        scopes: z.array(zScope).min(1),
        expiresAt: z.iso.datetime().nullish(),
        resourceMode: z.enum(['all']).optional().default('all'),
        resourceGrants: z.array(zResourceGrant).max(0).optional()
    }),
    z.object({
        name: z.string().min(1).regex(/.*\S.*/),
        authorityType: z.enum(['tenant']),
        tenantId: zUuiDv7,
        scopes: z.array(zTenantScope).min(1),
        expiresAt: z.iso.datetime().nullish(),
        resourceMode: zResourceMode.optional(),
        resourceGrants: z.array(zResourceGrant).optional()
    })
]);

/**
 * Token definition automatically bound to the authenticated tenant.
 */
export const zCreateTenantTokenInput = z.object({
    name: z.string().min(1).regex(/.*\S.*/),
    scopes: z.array(zTenantScope).min(1),
    expiresAt: z.iso.datetime().nullish(),
    resourceMode: zResourceMode.optional(),
    resourceGrants: z.array(zResourceGrant).optional()
});

/**
 * Created token metadata and its one-time bearer secret.
 */
export const zCreateTokenResponse = z.object({
    token: zToken,
    rawToken: z.string()
});

/**
 * Cursor-paginated API token metadata without bearer secrets.
 */
export const zTokenPage = z.object({
    data: z.array(zToken),
    meta: zPageMeta
});

/**
 * Browser runtime configuration used to create or reopen the session.
 */
export const zBrowserConfig = z.object({
    channel: z.string().min(1).regex(/.*\S.*/),
    args: z.array(z.string()).optional()
});

export const zInitialBrowserScrollPosition = z.object({
    x: z.number(),
    y: z.number()
});

export const zInitialBrowserElementPathStep = z.object({
    tag: z.string().regex(/^[a-z][a-z0-9-]*$/),
    index: z.int().gte(0)
});

/**
 * Semantic element identity with a structural fallback. It is not a CSS selector.
 */
export const zInitialBrowserElementLocator = z.object({
    tag: z.string().regex(/^[a-z][a-z0-9-]*$/),
    id: z.string().optional(),
    name: z.string().optional(),
    inputType: z.string().optional(),
    autocomplete: z.string().optional(),
    ariaLabel: z.string().optional(),
    placeholder: z.string().optional(),
    path: z.array(zInitialBrowserElementPathStep).max(256)
});

export const zInitialBrowserControlSelection = z.object({
    start: z.int().gte(0),
    end: z.int().gte(0),
    direction: z.enum([
        'forward',
        'backward',
        'none'
    ])
});

export const zInitialBrowserControlState = z.object({
    locator: zInitialBrowserElementLocator,
    value: z.string(),
    checked: z.boolean().optional(),
    selectedIndices: z.array(z.int().gte(0)).optional(),
    selection: zInitialBrowserControlSelection.optional()
});

export const zInitialBrowserContentEditableState = z.object({
    locator: zInitialBrowserElementLocator,
    html: z.string()
});

export const zInitialBrowserElementScrollPosition = z.object({
    locator: zInitialBrowserElementLocator,
    x: z.number(),
    y: z.number()
});

export const zInitialBrowserSelectionEndpoint = z.object({
    locator: zInitialBrowserElementLocator,
    nodePath: z.array(z.int().gte(0)).max(256),
    offset: z.int().gte(0)
});

export const zInitialBrowserDocumentSelection = z.object({
    anchor: zInitialBrowserSelectionEndpoint,
    focus: zInitialBrowserSelectionEndpoint
});

/**
 * Sensitive top-document state replayed during initial navigation.
 */
export const zInitialBrowserDocumentState = z.object({
    version: z.literal(1),
    windowName: z.string().optional(),
    historyState: z.string().optional(),
    controls: z.array(zInitialBrowserControlState).max(10000),
    contentEditables: z.array(zInitialBrowserContentEditableState).max(10000),
    scrollPositions: z.array(zInitialBrowserElementScrollPosition).max(10000),
    focus: zInitialBrowserElementLocator.optional(),
    selection: zInitialBrowserDocumentSelection.optional()
});

export const zBrowserCookieSameSite = z.enum([
    'Strict',
    'Lax',
    'None'
]);

export const zInitialBrowserCookiePartitionKey = z.object({
    topLevelSite: z.url().regex(/^https?:\/\/[^\/]+$/),
    hasCrossSiteAncestor: z.boolean().optional()
});

/**
 * Cookie imported into the new browser profile.
 */
export const zInitialBrowserCookie = z.object({
    name: z.string().min(1),
    value: z.string(),
    domain: z.string().min(1),
    hostOnly: z.boolean().optional().default(false),
    path: z.string().regex(/^\//),
    expires: z.number().gt(0).optional(),
    httpOnly: z.boolean().optional().default(false),
    secure: z.boolean().optional().default(false),
    sameSite: zBrowserCookieSameSite.optional(),
    partitionKey: zInitialBrowserCookiePartitionKey.optional()
});

export const zBrowserStorageEntry = z.object({
    name: z.string(),
    value: z.string()
});

export const zInitialTargetStorageOrigin = z.object({
    origin: z.url().regex(/^https?:\/\/[^\/]+$/),
    entries: z.array(zBrowserStorageEntry)
});

/**
 * HTTP page and target-scoped state opened during session creation.
 */
export const zInitialBrowserTarget = z.object({
    url: z.url().regex(/^https?:\/\//),
    sessionStorage: z.array(zInitialTargetStorageOrigin).optional(),
    scroll: zInitialBrowserScrollPosition.optional(),
    documentState: zInitialBrowserDocumentState.optional(),
    openerTargetIndex: z.int().gte(0).optional(),
    active: z.boolean().optional().default(false)
});

/**
 * Object-store key path. String paths contain one value; array paths contain at least one.
 */
export const zInitialIndexedDbKeyPath = z.object({
    kind: z.enum([
        'none',
        'string',
        'array'
    ]),
    value: z.array(z.string()).optional()
});

/**
 * Index key path. String paths contain one value; array paths contain at least one.
 */
export const zInitialIndexedDbIndexKeyPath = z.object({
    kind: z.enum(['string', 'array']),
    value: z.array(z.string()).min(1)
});

export const zInitialIndexedDbIndex = z.object({
    name: z.string(),
    keyPath: zInitialIndexedDbIndexKeyPath,
    unique: z.boolean(),
    multiEntry: z.boolean()
});

export const zInitialIndexedDbRecord = z.object({
    key: z.string(),
    value: z.string()
});

export const zInitialIndexedDbObjectStore = z.object({
    name: z.string(),
    keyPath: zInitialIndexedDbKeyPath,
    autoIncrement: z.boolean(),
    indexes: z.array(zInitialIndexedDbIndex),
    records: z.array(zInitialIndexedDbRecord)
});

export const zInitialIndexedDbDatabase = z.object({
    name: z.string(),
    version: z.int().gte(1),
    objectStores: z.array(zInitialIndexedDbObjectStore)
});

export const zInitialCacheStorageEntry = z.object({
    url: z.url(),
    requestHeaders: zStringMap,
    responseHeaders: zStringMap,
    responseStatus: z.int().gte(100).lte(599),
    responseStatusText: z.string(),
    responseBody: z.string()
});

export const zInitialCacheStorageCache = z.object({
    name: z.string(),
    entries: z.array(zInitialCacheStorageEntry)
});

export const zInitialOpfsFile = z.object({
    path: z.string().min(1),
    body: z.string()
});

/**
 * Profile-scoped browser storage imported for one exact HTTP origin and ancestor partition.
 */
export const zInitialStorageOrigin = z.object({
    origin: z.url().regex(/^https?:\/\/[^\/]+$/),
    ancestorOrigins: z.array(z.url().regex(/^https?:\/\/[^\/]+$/)).max(32).optional(),
    localStorage: z.array(zBrowserStorageEntry),
    indexedDB: z.array(zInitialIndexedDbDatabase).optional(),
    cacheStorage: z.array(zInitialCacheStorageCache).optional(),
    opfs: z.array(zInitialOpfsFile).optional()
});

/**
 * Profile-scoped browser storage imported before initial browser targets are opened.
 */
export const zInitialBrowserStorageState = z.object({
    cookies: z.array(zInitialBrowserCookie).max(10000),
    origins: z.array(zInitialStorageOrigin).max(100)
});

/**
 * ICE server configuration supplied to WebRTC consumers.
 */
export const zIceServer = z.object({
    urls: z.array(z.string()),
    username: z.string().optional(),
    credential: z.string().optional()
});

/**
 * Media capabilities currently available for the session.
 */
export const zSessionMedia = z.object({
    mode: z.enum(['auto', 'cdp']),
    webrtcProducer: z.boolean(),
    iceServers: z.array(zIceServer).optional()
});

/**
 * Tunnel endpoint for the `tunnel` upstream. Minted by the tunnel operator.
 */
export const zProxyTunnelConfig = z.object({
    url: z.string().optional(),
    auth: z.string().optional()
});

/**
 * Session egress proxy assignment. Omitted for direct egress.
 */
export const zProxyConfig = z.object({
    upstream: z.enum([
        'direct',
        'proxy',
        'tunnel'
    ]).optional(),
    url: z.string().optional(),
    tunnel: zProxyTunnelConfig.optional(),
    bypass: z.string().optional()
});

/**
 * Configuration for a new retained browser session.
 */
export const zCreateSessionInput = z.object({
    baseSnapshotName: z.string().nullish(),
    label: z.string().nullish(),
    browser: zBrowserConfig,
    initialTargets: z.array(zInitialBrowserTarget).max(50).optional(),
    storageState: zInitialBrowserStorageState.optional(),
    tags: zStringMap.optional(),
    proxy: zProxyConfig.optional()
});

/**
 * Stored session egress proxy assignment. Secrets are write-only — tunnel auth never appears here, and an upstream proxy URL comes back with its password masked.
 */
export const zSessionProxy = z.object({
    upstream: z.enum([
        'direct',
        'proxy',
        'tunnel'
    ]),
    url: z.string().optional(),
    tunnel: z.object({
        url: z.string().optional()
    }).optional(),
    bypass: z.string().optional()
});

/**
 * Replacement session egress proxy assignment.
 */
export const zUpdateProxyAssignment = z.object({
    upstream: z.enum([
        'direct',
        'proxy',
        'tunnel'
    ]).optional(),
    url: z.string().optional(),
    tunnel: zProxyTunnelConfig.optional(),
    bypass: z.string().optional(),
    drain: z.boolean().optional()
});

/**
 * Owner-visible role-scoped secrets used to build collaboration links.
 */
export const zSessionCollaborationCapabilities = z.object({
    editorToken: z.string(),
    viewerToken: z.string()
});

/**
 * Browser session state, retention metadata, tags, and currently available access credentials.
 */
export const zSession = z.object({
    id: zUuiDv7,
    tenantId: zUuiDv7,
    baseSnapshotName: z.string().optional(),
    label: z.string().optional(),
    status: zSessionStatus,
    browserChannel: z.string().optional(),
    media: zSessionMedia,
    createdAt: z.iso.datetime(),
    startedAt: z.iso.datetime().optional(),
    stoppedAt: z.iso.datetime().optional(),
    deletedAt: z.iso.datetime().nullish(),
    expiresAt: z.iso.datetime(),
    lastConnectedAt: z.iso.datetime().optional(),
    suspendedAt: z.iso.datetime().optional(),
    tags: zStringMap.optional(),
    cdpUrl: z.url().optional(),
    sessionToken: z.string().optional(),
    collaboration: zSessionCollaborationCapabilities.optional(),
    proxy: zSessionProxy.optional()
});

/**
 * Cursor-paginated browser sessions.
 */
export const zSessionPage = z.object({
    data: z.array(zSession),
    meta: zPageMeta
});

/**
 * Ordered session IDs for a tenant-scoped bulk lookup. Missing, foreign, and deleted IDs are omitted from the result.
 */
export const zSessionBulkInput = z.object({
    ids: z.array(zUuiDv7).max(100)
});

/**
 * Sessions found for the requested IDs, preserving request order.
 */
export const zSessionBulkResponse = z.object({
    sessions: z.array(zSession)
});

/**
 * Newly created session and its one-time initial access credentials.
 */
export const zCreateSessionResult = z.object({
    session: zSession,
    cdpUrl: z.url(),
    sessionToken: z.string()
});

/**
 * Updated session and operation-specific live access credentials when available.
 */
export const zSessionMutation = z.object({
    session: zSession,
    cdpUrl: z.url().optional(),
    sessionToken: z.string().optional()
});

/**
 * Whether the remote browser cursor is composited into session media.
 */
export const zCursorVisibility = z.object({
    visible: z.boolean()
});

/**
 * Top-level target and optional recording settings.
 */
export const zCreateSessionRecordingInput = z.object({
    targetId: z.string().min(1),
    fps: z.int().optional(),
    bitrateKbps: z.int().optional(),
    codec: z.enum(['vp8', 'h264-va']).optional()
});

/**
 * Destination for a running tab recording.
 */
export const zRetargetSessionRecordingInput = z.object({
    targetId: z.string().min(1)
});

/**
 * One logical recording of a top-level target.
 */
export const zRecording = z.object({
    recordingId: z.uuid(),
    mode: z.enum(['tab', 'viewer']),
    targetId: z.string(),
    captureGeneration: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    status: z.enum([
        'starting',
        'running',
        'stopped',
        'failed'
    ]),
    stopReason: z.string().optional(),
    relativePath: z.string(),
    startedAt: z.iso.datetime(),
    stoppedAt: z.iso.datetime().optional(),
    sizeBytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    fps: z.int().gte(1),
    bitrateKbps: z.int().gte(1),
    codec: z.enum(['vp8', 'h264-va'])
});

/**
 * Regular file retained with a browser session.
 */
export const zSessionFile = z.object({
    name: z.string(),
    relativePath: z.string(),
    size: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    modifiedAt: z.iso.datetime(),
    mimeType: z.string()
});

/**
 * Session file path and requested signed URL lifetime.
 */
export const zSessionFileDownloadUrlInput = z.object({
    relativePath: z.string().min(1),
    ttlSeconds: z.int().gte(1).optional()
});

/**
 * Signed attachment URL for one session file.
 */
export const zSessionFileDownloadUrl = z.object({
    url: z.url(),
    expiresAt: z.iso.datetime()
});

/**
 * Snapshot metadata created from a stopped, retained session.
 */
export const zPromoteSessionInput = z.object({
    name: z.string().min(1).regex(/.*\S.*/),
    description: z.string().nullish(),
    force: z.boolean().optional().default(false),
    tags: zStringMap.optional()
});

/**
 * Reusable retained browser filesystem state. Deletion is soft until the retention deadline.
 */
export const zSnapshot = z.object({
    id: zUuiDv7,
    name: z.string(),
    tenantId: zUuiDv7,
    description: z.string().nullish(),
    parentSnapshotId: zUuiDv7.optional(),
    promotedFromSessionId: zUuiDv7.optional(),
    createdAt: z.iso.datetime(),
    deletedAt: z.iso.datetime().nullish(),
    expiresAt: z.iso.datetime().optional(),
    tags: zStringMap.optional()
});

/**
 * Cursor-paginated snapshots.
 */
export const zSnapshotPage = z.object({
    data: z.array(zSnapshot),
    meta: zPageMeta
});

/**
 * Snapshot returned after a mutation.
 */
export const zSnapshotMutation = z.object({
    snapshot: zSnapshot
});

/**
 * Replacement snapshot description.
 */
export const zUpdateSnapshotInput = z.object({
    description: z.string().nullish()
});

/**
 * Complete replacement tag set. The map may be empty to clear all tags.
 */
export const zReplaceTagsInput = z.object({
    tags: zStringMap
});

/**
 * Immutable tenant-scoped audit or lifecycle event.
 */
export const zEvent = z.object({
    id: zUuiDv7,
    tenantId: zUuiDv7,
    resourceType: z.string(),
    resourceId: z.string(),
    type: z.string(),
    message: z.string(),
    data: z.record(z.string(), z.unknown()),
    createdAt: z.iso.datetime()
});

/**
 * Cursor-paginated tenant events.
 */
export const zEventPage = z.object({
    data: z.array(zEvent),
    meta: zPageMeta
});

/**
 * Requested page size. Omitted or `0` uses 50. Values above 100 are accepted but clamped to 100.
 */
export const zLimit = z.int().gte(0).default(50);

/**
 * Opaque `nextCursor` from the previous page. Reuse it only with the same operation and filters.
 */
export const zCursor = z.string();

/**
 * Include soft-deleted sessions when `true`. The default is `false`.
 */
export const zIncludeDeleted = z.boolean().default(false);

/**
 * Legacy switch that includes active and deleted resources when `true`. Ignored when `deleted` is supplied; prefer `deleted=all`.
 *
 * @deprecated
 */
export const zLegacyIncludeDeleted = z.boolean().default(false);

/**
 * Select active resources, deleted resources only, or both. The default is `active`.
 */
export const zDeleted = z.enum([
    'active',
    'deleted',
    'all'
]).default('active');

/**
 * Select active tokens, revoked tokens only, or both. Omitting the parameter is equivalent to `all`.
 */
export const zRevokedFilter = z.enum([
    'active',
    'revoked',
    'all'
]).default('all');

/**
 * Tenant selected for a tenant-scoped operation. System administrators and account sessions may provide this header. A tenant API token uses its bound tenant and may omit the header; selecting a different tenant is forbidden.
 *
 */
export const zSelectedTenantId = zUuiDv7;

/**
 * UUIDv7 identifier of the tenant.
 */
export const zTenantId = zUuiDv7;

/**
 * UUIDv7 identifier of the API token. This is not the raw token secret.
 */
export const zTokenId = zUuiDv7;

/**
 * UUIDv7 identifier of a user.
 */
export const zUserId = zUuiDv7;

/**
 * UUIDv7 identifier of the browser session.
 */
export const zSessionId = zUuiDv7;

/**
 * UUID identifier returned when the recording started.
 */
export const zRecordingId = z.uuid();

/**
 * Human-selected snapshot name within the tenant.
 */
export const zSnapshotName = z.string().min(1).regex(/.*\S.*/);

/**
 * Repeatable tag key. Each entry pairs by position with `tagValue` and, when supplied, `tagOperator`. Multiple predicates are combined with logical AND.
 *
 */
export const zTagKey = z.array(z.string().min(1));

/**
 * Repeatable tag value paired with `tagKey`. `eq` and `neq` accept one value. `in` and `not_in` accept comma-separated values in the matching entry.
 *
 */
export const zTagValue = z.array(z.string().min(1));

/**
 * Optional operator paired by position with each tag predicate. Omit the entire parameter to use `eq` for every predicate. If supplied, its entry count must match `tagKey`.
 *
 */
export const zTagOperator = z.array(z.enum([
    'eq',
    'neq',
    'in',
    'not_in'
]));

/**
 * Tenant display name. The JSON body must not exceed 1 MiB.
 */
export const zCreateTenant = zTenantInput;

/**
 * Replacement tenant display name. The JSON body must not exceed 1 MiB.
 */
export const zUpdateTenant = zTenantInput;

/**
 * User profile and deployment-level authority.
 */
export const zCreateUser = zUserInput;

/**
 * Replacement user profile and deployment-level authority.
 */
export const zUpdateUser = zUserInput;

/**
 * Tenant-bound action scopes granted to the user.
 */
export const zUpsertTenantMembership = zTenantMembershipInput;

/**
 * System administrator or tenant token definition. The JSON body must not exceed 1 MiB.
 */
export const zCreateAdminToken = zCreateAdminTokenInput;

/**
 * Token definition bound to the authenticated tenant. The JSON body must not exceed 1 MiB.
 */
export const zCreateTenantToken = zCreateTenantTokenInput;

/**
 * Browser session configuration. The JSON body must not exceed 64 MiB.
 */
export const zCreateSession = zCreateSessionInput;

/**
 * Ordered UUIDv7 session IDs to resolve. The JSON body must not exceed 1 MiB.
 */
export const zSessionBulk = zSessionBulkInput;

/**
 * Complete replacement tag map. The JSON body must not exceed 1 MiB.
 */
export const zReplaceTags = zReplaceTagsInput;

/**
 * Replacement session egress proxy assignment. The JSON body must not exceed 1 MiB.
 */
export const zUpdateProxy = zUpdateProxyAssignment;

/**
 * Snapshot metadata created from a retained session. The JSON body must not exceed 1 MiB.
 */
export const zPromoteSession = zPromoteSessionInput;

/**
 * Session file path and optional signed URL lifetime. The JSON body must not exceed 1 MiB.
 */
export const zCreateSessionFileDownloadUrl = zSessionFileDownloadUrlInput;

/**
 * Ready top-level target and optional recording settings. The JSON body must not exceed 1 MiB.
 */
export const zCreateSessionRecording = zCreateSessionRecordingInput;

/**
 * Ready destination top-level target. The JSON body must not exceed 1 MiB.
 */
export const zRetargetSessionRecording = zRetargetSessionRecordingInput;

/**
 * Remote cursor visibility. The JSON body must not exceed 1 MiB.
 */
export const zSetCursorVisibility = zCursorVisibility;

/**
 * Replacement snapshot description. The JSON body must not exceed 1 MiB.
 */
export const zUpdateSnapshot = zUpdateSnapshotInput;
