#!/command/with-contenv sh
set -eu

if [ -z "${APERTURE_EXTERNAL_BASE_URL:-}" ]; then
  echo "APERTURE_EXTERNAL_BASE_URL is required" >&2
  exit 64
fi

install -d -m 0750 -o aperture -g aperture \
  /home/aperture \
  /var/lib/aperture \
  /var/lib/aperture/artifacts \
  /run/aperture \
  /run/aperture/state \
  /run/aperture/traefik \
  /run/aperture/traefik/dynamic
install -d -m 0700 -o aperture -g aperture /run/aperture/user
