// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7P3/chs3ti+KvwqK51RlZg5JUY6TSeTadb6K5GS0x461JTmza8c+ItgNkoiaQKeBlsy4XPV9iPsu9//7",
	"KPdJbmEtAI3uRpNNibLj7MyuPSOz0Wj8WFhrYf34rPeDRK5yKZjQanD0fpDTgq6YZgX866QslCzMXylT",
	"ScFzzaUYHA1e5fTXkpGpYO80tpmSeSFXRC8ZyQt2y2WpSE4XbEwuWKkY4ZpIka3JHddLaKXoihGZs4Ka",
	"PgkVKZnzzHx4PBgO2Du6yjM2OBqw9b//kqx+WqY//HTzH//5H/wVP1u/PD178uLq+MsXV8+//On0+frV",
	"L8d35v//xc/U2Sq7OftF8penz7/6r1/M/x3rl6fHdy9PJl+a/31xtbh7eWp/C/7/TEwGwwE3s/u1ZMV6",
	"MBwIujIjSHARhgOVLNmKmtXQ69w8UbrgYjH48GE4OGUZ0yxtL9Uly1iiCU00v2WkYEqWRcLUkKT4RvUT",
	"LNCQyILMpF6OydWSkZTNaZlpwhWZYhfTcccwbX+1cdrXB0cDfNmsrChXg6Ofqx+q92iWDd4OI5M7E0lW",
	"pqxzjvY5UXKuR25eiinFpVDkbskEmeqiZNP2pOY0U91z4vUPR6cGPfhRz6TMGBUw7BdsQZN1bPB5wRIK",
	"/zLDGjamg+8Rdcd1YoiVamIHotw+GnJtb2BtpmcLIQuW2h9t46mZtCrzPOMsfWaOypwV/um/0Sx7rLXg",
	"K67bO3fBfi2ZMrMwh5Uo/hsbk1crrs1PsiDTyZSUiiny1WRMfqJZaZZgJm8ZOZxMCC0YoUnCctN6VmqS",
	"ZHSVs5RoaZ7XDvJXk/i0MhhYdDbmlRUXfGUoduKnxYVmC1bAtC5YIouUi8VZhCxfvz47JTxlQvM5ZwUp",
	"mC4L4bbEMKHCvU6UpoVmqV/8nOplNcgi+MxwULBfS15U1FMNfS6LFTXHrSy5adk+ShfsVt6w9Htgddu4",
	"hZY3TKghKfAl++8mn4DtMnMA5uv4tyE0M85bmjGhzY5MN1GX/UQX98iyGOuoXupkHTghll4xQYWO7RI+",
	"Ico2JHNZEEo0/DpSiTT05OXEmFyulWYrQlNDGUoXVMtCwXmkSSJL6MkynhVdk7yQtzxlRC+5IktGU1aM",
	"ybHtnhyfn+GiIpFzrchMliJ1z023phe54hqWF3t4ZkdrFp2SlM/nrIBFxre4MpOY8TRlYvxG1MTZ5PDb",
	"+dfJfDKaTCaT0d/Nf31j/mtS/efQbRF+rNqj/xwd56zQZcFGuGijs/qG/c+CzQdHg/9xUMn0A3yqDsxh",
	"uP273RNYoK4jc/v38NDIOUx8Vsg7xQq3uB3nRPmeN52SvsMUNFdLqX+Evpsj/Ue5omLkqUbZxsSMBLQM",
	"jkcc96SuUyi+ECwdcTGaUcXiU4H/2TSLFRcvmFjo5eDocGhe1qww3Yz/9ubN5fhv0dN/RRf/ZOsYG84Z",
	"1XSWMaLpgtyw9Zg8p8mSMKGLNckpLxSZrUkuFQd1CdSoqaYL4MlTQ6hDZGtOuAzh8Ss4OLKYjsnLMtM8",
	"z0A/S7kRfwoYeCJXMw5c0fSZyQVPaEaOfzxtkO7PAyZueSHFigkNK7Mwg39rmuSZTJlbohh70TjxcP24",
	"ZivVXsjGovkfaFHQtfm30mvYRMNrB7imbpYxRdX8QTPLQWQBa2mkVXMxmVlus/h+eZCzAhGZ01CEzFVL",
	"wzHIlP06BYbFbpnZp+rVs3mwE4av4E4ih1qVSpMVNdrFFFdm2l7sX5Eue6+vX4ToIjveDd0K1/lwIKS+",
	"xq/cZ+GB+raS861p5RbeUy7MGlfQsNmpgL9AmyBSMHxrTKZcuAYwVN8mkasVHSlmNsVwgFvUTuyxh9U1",
	"/BnWvbW6eSHTMoHhDgesHN0xpUeHQ1aOEvMCzUaH/VceV+FRaLtTanYy6orfRZiadv3tgT1fGbm509C8",
	"tDXXAK6MnBQSD1hB76wgViwpWOf47Tf3MPzXihW9R0/NaS86BlViTw8e0wfsgSn9nUw5wwt4wahmx0bZ",
	"gfU2vyVSaMOCj94PqOEwCWhGB78oCY/7fbXZ8ZnIS42DaGikEX3L6J5W18FNS9mcC44Kmrnh/fvlqx/J",
	"TKZrZHVml9m7hLGUHJKX/Ltxa7E+DO1UrW6y53k6jadrkt/VtRuSSDHni9LpnJun9PXTfnM65QVLtCzW",
	"jzM5333nLM+pXrqzmLrWRpQl0M+etu57nrFTeScySdPXFy/2Ntl49910a7dyzo3KY2ZuhIh0+gCqgOT1",
	"xQuS8TnTfLWv+fsr6eNsc3Xj7Zr5BaOp2dZ8lLFblhFNiwXT9ekHF18Gl0f10NmjqNrbnK3k65qjvTSm",
	"XOUZXYPSv58JPAaXDXrunlCDj7p7qITTSku9NPIIjFZOxD9wvkYA7m2iIE275mYemos4HEW0nOWZXJt7",
	"hCVRMz9ZcL2OjvelvA2Zy94G3ei3c/wnZQHXezN0we68lPCs5f5bcV7Ildy/1Kt3280j3aV5xTRNqaZW",
	"EqRozKekYJrC3dBd++890QuWZzRhV3Sh9jbLoM/uvZNG5deMFNh4BXYauiArmj9kNshUH43ld31gC9NP",
	"mdJcoEelKQDuP1s7iO/K7Gbf0tz02TmnV0XKzJXRquTu2J2dKsMXC6ZkdsseMi3ru7q0InCPk2v0vGHb",
	"zDkl6GLyshh0siUViwfM7nWeUs3OC/luf/pm0OcJaMjxKVUHzW0ZWxRMKSMD3q13U663TdCxsD3P0XW7",
	"YeOCWTo2GjR56Lw+rjoVzkbvU7XCyXw8VSOcSPlAteN1bu4YgYLQZBArsKjSQh/MZbEaGQFan0ZeyJwV",
	"2t7l564Lbx3y7qIZFxSMSlssRNUPcvYLS+JcUzBzP1/JgjkNpdBqTF6JbO1cRBqegKncLIydE5iDSwWO",
	"SfMO2OpkqQkNmheMcPRsdiyaYoVGcnvJVjNWqCXP90zHVcdbLggj1KIpWPoIOJMUWRRUaOZ1a2fZaUwF",
	"rDEql0Lhpj0vCtmHiK2REd4J1HYQ4u4D7weqXK3Mjh8Nnk4Oyf/zf5MZowXYlc01YMWVMvs/HNw6Ayur",
	"Pp8CQdS6vvaDHw5WTCm6aLchvg0sV/0hXD+ev8v7jY/Zhv3HB+9dV+91DrL+ARipdT2dmYsRzfhv0PB7",
	"yrPmUL+aPIGhOmOOpoUuc/O/RsTKMkuBac0YoWiZ3zQB28s1r332eo7fDWfgvldvSWzLcAqXZkQ9Ro6v",
	"GgKFOfQZJjTcNLpmnzAuLlQ5n/OEM6Evzelo7v2XZliOcPAA9aHOsN9reKs2pvAxduqGo1khaObPWrhC",
	"EzOUUrB3ufX4seLWzqss2ObRYLfX+KA+EnzkesMWdjC3NOPphTfJrpuLAyOyzSrpuHkk0Pja2nmvbftw",
	"PNibbYAdWtMwRpkcJwlT6pQJ3j6pdrewoTOvW3a3aVjulWsKnV+n2Hs4MN8rNiG2CQzNanlx9nE4wUHV",
	"L5J9WIhtGuUazW7CcZzhGl6aY99coW/NYKqoM7fcc1kYHRxu+cAu+ozLbaZ7oT06Du4oWn0HWZH5GsQj",
	"+IHUxv+j1N8bsdUc+1Mzdte1PYRG0s9lwfhC9BmykPp6Dn3HhmuoBZ/CcFARxAAOHNY5KzA0KEp4NY+A",
	"d8xTIfWSOX/BpkFii2vlPgijzf0nwxHrMGbEDb1qGht+l/SdBEPHgAsSCNP+g41K4NY46zIYiKJTnDUY",
	"zJyzDGKyvBd60/iqrmNCoXqKHO/NGwHaHVe1EX7o68N6XrHNuhp2fH6GXxiT7woqkiWR6J/9x9XVORyH",
	"EoN3FLqLp9jYTGI6HkDcmrfR9dXA+g056Ph7K0Ji48cbQiDSy4Ip8P07jyaMmDBxyzKZs2dVIy4URh4x",
	"UpRCoLEdTxrEDjSnZkQMThpvHmzT3WPzxOuTgPeJ0tIGPgDvsRJmaDiUkzaySFEX3nZx6emniV5gKj37",
	"Z9vz2x63mkscPb5QESaM5rhMuX5+a1emPnZU/QPFvDq7K3+LGJdwa2Fp7AZGEy2tpxif/eweDgeizLLB",
	"W9foao0K1GbLLBcJz2kGjT8MB9bieqxrF0Jzax5pDiFIrRG5iyZNU47+nPNgzuh7bizocMDTvo7oStfY",
	"NmvXzk18wxJH77ZBdIMU7NV8cPRzzyH6EGwYy4e3TcKC6MtqU4aODhpjtmsZ7sLbyNpVBHYO/LNJZG5D",
	"ep2PgFojESArprdb9+mCvTTtmrO2k4E+4vPQy5eReB3n4MgdcQJLhqil+ZzZWNSGKGuzCXpLeWa4ON69",
	"Vfs7x7WuKuJQxL9rLihUuFjO0YwmNyytBjY2LHeEKob/UdnIXvMiW+V6TWA5IVyjz45YW1tkN/wneh9r",
	"iOKpxby2l+F5Y1EhlndqKHlahSZXe7GkqMh7lUoKZubW78j4yW07MtVcWzMYtve2i7zAnOb4wSZZCpYZ",
	"WqzHZKogxOQaQkym4bau6NoHnhgVEnIHnA0P1QaMl8Z1VGMyxb9qvdBEu4BQKViLpG1smI2PC8cycCwK",
	"Q8HqvC3G0GwYycmSCsGy9gq4MJOiFIa329ED2cO+AxfCoOIgzrZ+ykQ0GvbE2tSNgLcfSXAUaMCthb8m",
	"y0KueLmKhqiGJAHfiu10faKqe6Z2EIowYaaZovrHVbCPtbG9HyS+z5/f+wwcN+APbz801yMJxtDrtDc2",
	"aZuK4vvftA7oDNm63zXPB1haq+gbwwMKJnN7/Dv3nxaLGGf1qgA5sYuFAZIiHWVcMEKLRWlWW42JCyIn",
	"BTPzUNUzzHUxo8y4PTRElTkrbrmSxUjemRv8jC3pLccgsOA05jLjyXpcD7McjTIqFv/GxOj1pVlAv0Fb",
	"IyGTrjNk961K5pityfSH51fkgOb8wBL/gdu1aSfl3yd8O0IXm8lC3nB2SVfskqMpwnGZS13wxLCQF/Td",
	"YDj4UQoWDcH9ztkNZUEX7LnQGDwW5witt2/j0bk+2A17dYG2P7JbVpBMLvCAwnVz3FqG4eDdSDGhOKSA",
	"BKbyBtdwX48tTzz2sJ0Y0gyJqVKN0JGhYqGJ1oAs0lxyZC6VnGycpKa4isqA2Lag1Ukd6w0B5xffn3z5",
	"5ZffEnPwlaar3IaTg5sXwplB3s9lQYQktNRyRTVP0KJVP0eDJ5MnX48m34wO/351+ORoMjmaTP5rMNx0",
	"W4hp63HJ4cLGR1TZmDj0+L1gFOLDjJTVBeWZ+cfdkmumcppYU8FK3qIfqBprnlFtBkacCN35oFU6+g9F",
	"XI98WSow46OyhwlD3cTQWw+8CD8Lyjh9d4YvTtocyg3yJRhc2tlSPcJobT5XQoXR70pV5YcSmmXyLuNK",
	"Yzqsy7yKplmZy7DMWddC2cRBp2cdoZ7V4NThsxqn3njVR9M97LFdqMPGQg0HpeC/lsw+3sAv6sfRzynC",
	"QHof5Ep7+/MI73CEXfKbnZB8pFP8/B1XmLeI36vyaJ2HFlNnw4M2xUxodzimzzAWocYLqjzHex36reTb",
	"Pvp9+oe2G46qdVibHqjm5kqALceNc4u5MPbCc3RXcM2m4JVHba6xlz874746KhiFbEH3b3i191HH4d3z",
	"wNdNPTTLdjD1vB1uNCJoSWZcpGD8p6aHbO0c+5b592Q3QWpMJ+d52xnS36HCnEai7FsafcEyaqZ0Ts3p",
	"eh8L2p+xTN6F9wI0hJJCSj0mL60vKKcFaPGQ1YcGrfrBLsGurA64uJU8Yap1rjervLWBdit2tajTzpuq",
	"taiD7BbsrvIQRjJNg+vhjCpWTwxtZ3PaHqrbUvsi4q8Xwd1yOLAe/CuIl8QbaFmYRkutc3V0cGAHMk7k",
	"6sCaqIBCMzqznbHkRpaaqJW8MTSqILUdFW3vkEzgXmD6fzscyIIvuMCPZTKhmVX2w/sv+lzR7FU5fQYX",
	"z0+PT66en8IQsJ/4WJFytY29DdM4zV7TBUoZVcItxU8C9r9Oqu3V7zDx+ZA4uORSVcshBtpFfch0iFJ1",
	"GMrUoZex3qSHSYRIL7OMipsogbSJoVuYBmTSx15gAx7bVNJ1v8KwW3uptuHH4Tp8oXyICoAv0LkObmV8",
	"lctCj8kFU2VmXTNkLo3kU4Sbs4W/PSMyZ4LBXZyJlImEM7SczVgVzs0LpXuLRBtpY+eB86yrw19F9GF7",
	"BrZm4I7mNDHcCtpbXziLb2b8OHXvaO6iXbfExlfhq+3D2X9hLsM3g/PVT75dwuhf0jwi4ux3PLM3PbcF",
	"maPfrZy4ET0euWjvmCrUEmEzbm407J+zXG3CGLnlKTPyGhoTLsgNz+SMa2XEN1EskSKtdGxzH6JESDHC",
	"TO1bFjABQzNcKE1F4gFlasTz9WQSgQwZgn88aQ/yJxgaPLQj2PgVe8G4zb8ZDAfLJ18/Hd3SupUYH7WU",
	"4vnmFZoXdMUeZzlii4H7HUuDPWtl7xbxtDKIxDcUMt5Rm/Df7kG/Ci7WzTH+yO6ytedx7rA415UUeKFy",
	"cXkucikpGMyNZhFCTtL8dZHFfRdVAhaYWBk5ZbdXUoJxG61NfiuCLKE6R3PCmVob7DjUKJI0P9iOD3I4",
	"Ce+NZcFjZKaqhKIevvrgDZ//tpkj2bW0ydoEvPOEa8JXK5ZyqlnWuP/SXF27uZn/mJl9Mwn/czi59grN",
	"PayObsZDt4eNKXVTWSs9r4cl0t31aZate6TqtejsT/NDt/nBqYl3sriBIKc/bQ9/2h7ubXuI3/67jYuO",
	"KZgjf2ETACK3WCt0bLy+S59syR4bNl+BWjSu/vSug+G+cj14b93x+VktCj/OdZ+RjGqIYaSpj4sA5MX6",
	"UJvcWW/hzpMnu3HnIWJ1bN1aaNRSDexF1y9PdJ9auXu9UusAzaMRj9femJV0YWP9tPlzCZHkL/G1tkZ/",
	"VV1xvlAeABG/AozDb3OOPZEFU+bfakzOEClRUF0WNJuSUmhuJLEeIuyZa/qFIvJOuE5lAZTotXdz22QW",
	"J47eGB2zYInRhBIGMYe3XJmT317Hfy0ZBvCCDhiuKYQ3g28hNcp8Bhd/XTC6wphO/20V+BFDUMJwz933",
	"h27tY3vuQ0CbwYFUpLRIG7GYNR/xxfPLKzhDPug6ov75KNqtwa6nTFOetWaBHXQO/cT7ihrDNzx3RZMl",
	"F2xkji78gLMxd5KaD6gz88cFpMdybwbDbSk50ccVwl80paMzcWBrLPem+Gn7LAxWx9HUfsFGKQM0Qmp7",
	"xWZ0xa5dFIP/NWUZW+DcMG0R3igVK2r9wg8pVxCu4v7NVpRnYZclpgbdco09lsJHSEEAnotsq3UteZpc",
	"W0DCov1knsk7l1Tgfmtsig/lRngivcZ1NV0a1uJC1luR3x15J7G0gHbWxYwqdu0MerW29ScBAG3QL8a0",
	"2IVxD+QtKzK6vq5SibqSKmpdIdcGurOcpTac6tdmL9UTuOE3tksvy9VMmB2uLQSad8xCyEJfl0KVufmr",
	"NsM5z1h0+eDBrFTr5m/MaJ4q1sVK3jaWCR5pKa8zc1cOHrix/VpKTUNyrr0J0Kqxpx78B74L2mv0aV5I",
	"DXpd8BR9COYsYMJMsg6/0JGOti2ZLkpd1Y+N8xyjuLCDOCHmgIlhVxj/YR4F/bpRuuChBpmwW2B9rLjl",
	"CWs88xsTfVp9reNtN/r4Y39aZCkii5pIoQuZhae9lu/2NqavOQPEaKl1PsJEjHbKasWVj55ODreIkA1N",
	"nBjBJnG2cfR08m03szl6Onm6ZYeOvppMOlfl6KvJk210WG9TI2F81E0B+O1Ornz0dPJlVIS6B7UNs51t",
	"kua4kFG2fvTUvB0VQbiIGwQLdtuWRthnl/yy3caoFKcSOW2425sPBr68iXcfPX3ypJvv4zdisgJH3KG9",
	"4J5s4pXY8SZ+WW9RnZDDSUxE1FuHYiLypMHVj76a/L1THuE8OyVNpPdK2hw9PfyySy7XX+z6XoPrtl8K",
	"dIPIQyvt60+amkP9aTcVbZGc9VXcJOOOnj75NiKC7DjiIqv5cMN7zaXcJBnszLr1FDweEU0Zv9rSs/Gb",
	"W3R3PB7d+jvyiphOZbvv1MZtzxEd3o63cQnA/uoKO7aMKe3Bkw7FPWjR/EhbqTbT/ODudfY2eI+bHQZZ",
	"U7IEOOuqwbs8owjkFHFSbLpFQqfmrsgQFne2RmjjKunZwVrUTUDR+13LrupTSONw3NHxkzMN/mgXh+hj",
	"HGVBgkRUSG58p7tHRTpG1QzMNqtTjTR6F3e5gg0nx2pVWtTiGvo8LVM0u2d8zpJ1YuZ3y2Jm/VoyX8MC",
	"xFfo/YdXyR11tpmm+RtN9X+3pvove5jqd0wNbFjCzXBGKmcJn/MEYQxyujYMcEhUmSwJVZZeU6ByBc5I",
	"4JBxa+L7QcEopKQOVlSUNCOF1DbNvTMx8YFBYTCLALR3vBOxwss28boRTuI88GA8hXnEs0TrKZPbfKlU",
	"KZlwGlYPMccE6gasqLaxHIrIwAVxtc5ZI52hp7Owc7DxPC3nNSAJ1Wwhi3U4XF+/B08AsamD2bpCdrj1",
	"QWg2j80sK8E+n4Fr1HYcBKrQtHUOKofexsTRBxKOBRKFGB15J1Qwt4pa294jzQSYKy3tmGYY6jSXgDm1",
	"KOgKvXFLKtKMi0V0cmN7Peqiq1hWaw3Du5bLGtCg7ak6Az0zXWtJrq0kUSWLUU4XXAS+TbvfbV64U1Ls",
	"p8mHfQ4qk3WCh+E83g9coTn9/D4I1Rv8bfD2w7D2Syzsbuh//Zt39Mti0Xh3YJTgkaYzBfRZX0Xfqk2D",
	"NDFCCR4TKtIDWZC/EesdVRBB5zsG2B9MlXQwJzldMDTTY8xJPVPGGZuroUWC6EOce/rOuWifTJ5+M9wG",
	"fF+Fkh1OJptceu08VbcisQ39B6NZLIj2hUxoFmarLaEhTH+WlWy0KBjw94wRLpAJt2NPse7NiczMHX0w",
	"Q9D/pP5P00VYbstZVgbyZjAc3LICwzIGh+On48mgFWBZ+0QrmrgaP3zV7SUwXwe34kpUhS4DOzaYZDQb",
	"Iun5QSu+8kJC+AdwTWBwhh2AfwgMETt9G1es2+tUSxaNTLy4rcpy6YIabXEcK1bEhf0zmkDjDWCN6Gs7",
	"U6SXMTk2KpH5ZV5mXpEOhlMww1EUmcqbaTgKeRP9rKeHVgxpyRHspWAZo4oR25Kw1Yyl1uEWIosggmBd",
	"yCCNbRMqduqOCOyGVGMb1ogydurOEnYJ8FkR1efkuYPWqie/uuIohjP9i80urk5MA2WuLSqqV9uYrYhi",
	"/frixyCoa0yujIQjXMNZsK53xH+UDidIcQUtuCCZXDQqDu7o5y6LWAL05dXrH83+wejsCry+eKEaERK6",
	"LMSR+a8wEOzoy6d//+Z/64IKZajp38o03y151lxh47E6MBz3uKr05lEH7EhTyRBzwBIKqZsLm8ED1pTc",
	"qbE1KA5WLEpItfjaE0S7eZ5yuJT5CN06aSz1KmsvSnyrMpm4MkH9w3yfZwAn+sK+25yM63OII+k3rUJm",
	"HpgqAicCBkUHW2M5yFwWd7RAr1tyY/8UXYnDDOHDNlXPA6ZX6G3N2twCAAkZuGiqkfafd3wbIdSbBXgz",
	"VaDAnvatQrU4EylkvzQK9WxYqVadnnDz+g+ptfVhkvbOEY8V5XWnWje/L294FD3C/G5TDkC22GBGc1lz",
	"4XgWSTei6MsV5Q2IpXFdDd6iDdpoyEgxHsHfVfGPhl1jVLQKYrRpULXFTAOZU5KVit+yl+1tFeVqhru6",
	"lEq/Etk6VkKzwc0B+NKsCH7DSC1mFPBsTaY4/+nQw+Wqcoa/qbF/irGChonCdZfkGeWCmBE4fI422ZvL",
	"Q9f42q0dw9+y1jktNJiGbCG6XajXTP08fB/6Q4W72vuDQRik+X8OovHJAShCr+SbGpICnMCkLFi/lenA",
	"QbBU/6jwB0N3OuxC9T2j541dasg8qk4KqZRZjGORMGWZY3vqWuYv2C3L3Fo34saDbYKb6v8+Ojj4+f8c",
	"vP1f/3OrEK/1vH1apzIBjJENYo+KZLkrk/fdPbch+JBjIZNSPbifxnzt6FzvO8zYCbxmfSJLRZBSkdrG",
	"FiEUssXWLCVpaRbfpzAIessXnV6BmrrUHxCnh9bVvLFPIvlf1uH+kO969aDP9+6xy22VYMnN2Vl37NG/",
	"X776ccREIs2FS+miTIyem46STApG7Lu4ZeOetwWVFDLLzm3pyfsulp3IZa2zXqt2T82lfXzrt1erpR6+",
	"jWlPd1yk8u7HKExND4ZaXUQ9iQ3b1N5e2u1HtEEPkTO6ogJSKrAhcQEezmvnaIJmZE6zzGjmLl7X3J4o",
	"Obm8tLYZWcSwnDh94dIm28CTpZaJLV8TbcDT+M8iL7Uz7beedqIFOUF+f3I8p3p5qVleJ8QnX30dAdbL",
	"aMKWMktZEb/RUoDTCuTTz3T021vzX5PRt6O3f+shoOiiv9RtzqAlnLhI2bseF4V9jRu/13vgDU7QGv6e",
	"blDvgs2q9Oh15NfOu8q7gXlh+8S2zejeQ+k9gJZK8FirKmTqwR96Xki3HC85nyu269W+2iM/IN9Tj+Vq",
	"5FG37Kjm8ug86rMGBJm/ec7YHHJarL4za6TS04Jhunsa038sqsI91Q+4GvcRoYFLZpcP2QV6hTgNbR/I",
	"ZhRCO7nhRvdHNHG/7f2+ujq3iAMitUvrNgbVT1xip3z66zWgU0YxCdGwvv0abdE6zQXLpg+7jFlAKCCJ",
	"FMJVd7AfzTj4mY81WUmFlaHtq8517N0d7etP2tTB76HxOIUUYRZwUc+cNGhmyabsHWQYWdB7R8cuVxq8",
	"zLi4wSLYzOlNljpghjteaVrKoao5OiOHlBUjJC+//P6ACqVpllm/g906zFW3RxYICntThL1jSYlK8S5H",
	"BBe3dVBa5u1ohvZMyazUFlleFvC/l1Dg1dllvO+kkQLeTs+O4bwM+1ye+9i+Nx3dE5osmV0A+LstdJjQ",
	"xT34XNgzAklGVrZDOYxbONxAek6nA73Sugz/AaUXtiPOVagZVX0mV5vF3QnMhQ1iQyGa/OunPa9mrruH",
	"DOXS+xFX9B0e6K++/TY43odxVIr6+1fsnY6qxZbyN2f/Ryhu2Fzm9mxbc4gOqrHoG7YeeCFLT787pZoC",
	"Fk9/4FLsDNJbd6Zz/91XVScxUg8ur9XmbNWRnHHPX0lrQ+2zHF501Nfihq2dCrjLJOGPf9p3jU5RZpr7",
	"k9ZtJG5TFiROx16Kr4Abr3+z9u3eC/HPatoxUXrD1rbALp42+IeCUFFq4bzBzvoMEd8bj6kmGaOoNLSV",
	"lhuOPjKP+up4A5JI1F3vDMndrtgNkSyNhYTv9/Dd+AXrXCuk9BEU+PioSwbux+GeVm77YvVZpPDUH0WA",
	"QuWZSAq2svG/7QMC9+4HcB083hF+c88DHpztzrOLccT3HzPiQ23dg9bJry9ntXbViPrsmP16jCPuapG9",
	"Yeu+dtgOn9Dm/tFVdB+nkJlMj7P+6vz7S1fivIGwtR8dxxn5dgFqynG3Z1sEfl1tv7cFwFwIoUwDxDda",
	"ZR7uJAB2YL1dxLsxI7dR2+ZVV+jkFThc7kSt92Rp+N887BpIAIZXRcqgx7lCwcK3axedB/jYQqPAl08i",
	"PpZAn37IBQCvFhEuxd2pvDcz8epepPc6vuVu9Rq2XV1kPt+ZA/rj9qHLylP3bMdjfPfnU7XfbCzUhjMX",
	"uzA/+MLYd8H95x5hATbdLWN10yLx0ZCyUlCuwGgBpdjawC/kTJOEFpCKQIkNliezUhMhXU06B8DRARVS",
	"kQdUW8ZsNuUyZCBbc+u8u2FDImXq2vXd8AFC22T81kfikUJaK0y/WkG2jN+wd+W8av0BYfalrAbLM9aF",
	"AGwj0A0/F+wONFAcewhuHClDV8jVhtpVphfThFAyDQYB9DslBWAI1q09RgbUAJHHeTrfHq2kZRSKEEfQ",
	"D6nZpQwD2fVFaz6wIG59Rtmss1cAp9IySmM+f6Ij54PYnA+oO+qgrjxyM1N6hNZbXGOwBLZ3b0nVS1ls",
	"iPR2NlMwJPKgJFhtVWrV7cIQQThnG0ptoX2S/+ZwdmmeZ2tAQ1p6xEwgSWu4qX31q8mwMui4jIVOm8Fw",
	"INg7jWsXg8ujv5YeQ6lCjHxnV64VlFvYUr5BmxqdsPW//5KsflqmP/x08x//+R/8FT9bvzw9e/Li6vjL",
	"F1fPv/zp9Pn61S/Hd+b//8XP1Nkquzn7RfKXp8+/+q9fzP8d65enx3cvTyZfmv99cbW4e3lqfwv+/0xs",
	"DyZ37M7tdpTcalhZbfeEvOtGwyK6oLcsGwdwWIZUBGFUsXRIVMYXS52tzfLespQsMuD7mtCZLDU5fDKZ",
	"kPzdgRqS6ZwqjW+TX0ue3JivmNaIqjVFNFU9Jb+Uqxzq+BqtVGmWj8mxIDgdosArJQi9ZaDGqpyhjdx8",
	"hMARmfN36EtxJYfJimcZd4GM1VYqvGTBtAbD9wPoa3D0zWRiOLLr4KXC1OO3sXQd//bAzA5Rm3RHCYyu",
	"JFHruamfXjuWltG9NW3+jmU1/NpB/eRM6oenHZbZjDeGD0eLgOww/HDx2tVRzf4gXRELGFvbomdkgkRQ",
	"m8uXjalsnUkwhnhlgfOw2OAm+FlVIvH5aBS4GdWq6wXJ1O1aKS+ZXsp041eQ1SdLKrhaVZmNYeXYWpJN",
	"zj3MmORpAlqgUnjrNX/dmSt+zDDUqt2yuXRm2NhHwETz4Hk76Ta2iOPYJSyeO3HKVZ7RNaCbxvus/EoW",
	"sLloKBxB8cKwuMo94EvzjCfcFndXvcBKEaQUWnLtnn5+WKUQil3BtEZRd6tyoYNdKxntWMtkc2FPPDO+",
	"mg7Sbqvap5CuDVc+ka+/0t5dE9ciZvRLST8+P7NZ7v6015N+wnHD03qJVoftuqeB36eUsjlwscm+VqwI",
	"+UFk9Jun6tdmL7NrxnthojZ3GIyWO1ebN9xSIatxzlrcI6qD1dauE0vEAQBEuR1QSMoh69TFN8YEgtkW",
	"M1pAEq6D5IfNWkzwHKCDtpSTcdVIqouJr3mBd0GlZZ4b1dAXmIkXlml068qIYNn0eSF9bLYhCF+YQjME",
	"85vLImFe+RAdhWl8hYiqeDvM2H0BFjBWnKVdiaU23E4IcV+GJXg+dpSNC4WIB76hi5WgtVdqUmzXtenG",
	"E7erti1s6BSxkqpBCgg8QeBpLDAT4rGPySXTZGq49RTLE2DpFSgrXatOMyR3S54sEYncdAryhGtFtFzN",
	"lDYaP0h7RLO19OOubElVc9ePrGDaHBApjArMZRoPS+rIzUTQGRQ59cneH0y9RYP3AFPff2ETF9ZMNF2Q",
	"Fc3rhRPszMf96xGHNV0iUdwWmGRRMKUIFImpZyOPyUWZOVMMJiLChQ9q7sCK+wi1FdXJEu1qylGBwDjR",
	"Z6QU8Nhogv5XRRbS2nvwZlk1moKZdynNPVRpulZYHbkyHZlHddcDdmSnEqnDsjbKNi5BXrAEwb5isD8v",
	"2IIma/iCRYcQqR+mYjn16FHTZ1MQh8PpmDynyZIwoYu1x76niOFEijJjZApTmz4jlGSWYKfjKVkxChgV",
	"6yo1bkxOzk4vSEHFgpnb+JtyMvkygQWBPxmCzQNRMZIXzFyjVR1snrxWjEzL3GJOW3h6M5Bm3d+/jR3E",
	"YiMxsa15l7ukzgDdGdrpEZOrS1fQeGuPV9C0qlHkprjDxiouFhkbuTeJWtKcPYMiMl0rRk6wDunMEPVq",
	"BrzOwf2sxmQKB2dKZiyRwH7JnBsZM/3bFDf/llMyLYtsOiRTnOyU0OpPPxQELY+8zPUQscosNDmSHxIl",
	"NlOeUUyR1KfEegrGVUNZEGmPDBKekPhyqKBg44GrGeW3p17pHX+LkIlfwm6wrR77/Nrt64fmLronyiwB",
	"SoAfQeiZDczkHSsSav5ihn2rIUn5gmuEc0mpWjL1zK/H0FwM56WyJwqZjivbAPn+oZSqeKqPsuxFb353",
	"kb2+vngxdOABloo82U0dKe1wgJVMbtRXRwcHRpk8Mjv//4M+arAJh5Nv4hbKuLyAc9tGv6pYu6+kHzBz",
	"s8ooAxJ5G8WqgKftfqfI5w0nNX8d5bIwe3MH9l3zNfOrEePg+B6S6d/GAH33Dq8gVU4xXk7+Zi9hYm2l",
	"hPlFQA4rihcVihen6EAhCIonTtAVpBZqK83G5IWUubkPkbNzZfsq4DxazJd36yFRkkC3xAJSIkt2Eo3W",
	"vtrkwW6vanXcwiAhHnFB+GOdcpop1OqbMjIg8Tkg1NUF89ATfans1lKtKYwYJ4MHHdGQoIO7JTdLZBRA",
	"rnzrMTkWa700y8YyxZweKjz1w96gQZoLqLvvj0OgWVfVQKrVcdXxtlrYkbxwsTpVoZoA6X+I7TLUylmF",
	"x9ay8mdkJvUSU6SdSA5POtd4sqnr0Eyfi/Ckxw2TERycsH6KZ/622yUVqVrSGzYm/yq4ZiND3s885WLt",
	"h4diu8Tyxlc5VnyqZveX6Z36X2u6Kt/9L8+q8LDfqfaDv9YHFWmCXdeqg+mD+8H9dfK/1zWtomYIJngZ",
	"8kwdEheQlFEMA8sgelnIcrG8/2aGFPKFCjf0wlFUsxnW2EE0YvvQn7GPSwfHZMEEK3gSHPK/TJda50bm",
	"QuiD+QP21P/xVfXXcvpX9BAlfQlq2EVO5BwvNVVeg7l1WIgoIzK5mEvyl2lEjIIwMpJz+lfUzArDWwWg",
	"J31HFU/IFDofHYcOBpQ+ONkDO1czmYvvT8jht0++9RhDB876X1X6NGOwir1CX5rV1oxIdK5YuJSYYZG/",
	"wAt/HRLzt/kSrNrTp1/iv9THPkx9sjl8xc1oYSeSyQVPaqU1IfyhWVtxa53NzU7ohOa6LNgPhkhp3FB0",
	"DBXbwCGx8M0qA4cNrYiNy8f8cKEh+nBzApOvutlZObOrUubmOa6iUMhXdBYUH4K7tb1a84JYqFuw9dTn",
	"9YzccnYHPMO/ixV3bVxNIyvti8pc366Lac5S4i9UzDpsACIOW1iWZNdD0xkIdfP9OEyeL+La7fOq6Cmw",
	"dnu7FU0KqXziXbKEq3dtL8uSd4DbbqpQfhkEumwPgnmGii6GnRtmg2yavculanLpah8O/J+jr76asG+e",
	"TiYj9uTb2ejpYfp0RP9++PXo6dOvv/7qq6dPzdEd37FZ9Hqv+G/su7Vm9UDNfjQM0FcO3LkfHHMFK1hl",
	"GdBC2yI2vpyNtVGD2x7AxeMQhTK/sMDKLXxLD0yN0MseWtoGuyA2o6/jq2UOwQmg644HHR/Ld5vrLrVk",
	"W6clRFCsQLHb3+ArZtTqix0J0pewrYqhTV1f41+UFNMhUfSWpRhjY52KWK74L9OK9tBKxVM0UQGVTcnS",
	"3Ho629Q/81eIOMThzpgaOhkNn7IF3MwbQ3t6FisAU65Gw831M2VEzrFJK0AGn4pgvswl+XprDi9c+BEc",
	"w6HhZ8kN9qUs54LFVGiy9PCAvkOVAGAqMpHU6B8MlAYpbI3zitrM8ngnDFSWNpdQ6JIStzokkWWWGk55",
	"VxhlQIzJJWv0pMii5GlV7xhNKfviGLV92ir4Q25spVBwAmKyd1gBbdbYachXUOgNa2Leyc6NaobLGWgX",
	"HUSq8W6wYF/uzL4AzWs5dFiZ1cHxOw8lJlW1U/69iOmDrzowxV+ylFOEybZnEQZW3zz46aCLda9kCmJ7",
	"I7h+fXp5Ocu4WsYR9r8ZTQ6hGO5XOyHsx3033/PMuorcNd9XhSGV9a+DVh8m0jYL5/OA/dny6xsjVM+p",
	"UoQDC0T/oCELrOrrwmXhpvXYcpqKdCbf9Z2Tje/WtSqbPsUE+xqSUqTMoQ28YymZHtjGB7ACU7sEiN/j",
	"qwPM1jVjIFqGwuUrStHY2Xq/B4+jxnQQIYS4ckFmRsupDetw8vSbr/7+9c66+ycQumNyPAN54gNkOuXE",
	"x2H/VUSKx2M1LPftVjAfjNSwARxNxm92scbYhhULjfN78GRf0YXqiq13jlXr9IarnaYLopgeEyMQVjR3",
	"yBkYEWZOesZoQWhm1LEGGvJ77/2tRybkhUzLxEq2gi3w86wcQTz4YSRiYX9e5JOG93hM/snWqLdAhp1C",
	"56TLaRVSjAJPebKkBU002O4j2EuqY+XD6Lf2PRrL4WtpU9fqxcUdo5BF5dWfrUGq2hQTDBaq1S9plYqu",
	"FRjpFXnUqvPRJ/4Og6la6k5XoYlNi/XSX85tdIfZ+8GwK/7fLVcViZZAyAYsrbkkrpvV2sHVZ7RJVo+H",
	"rEUiwSd9IGQj/sj/HDnxFxurpFw1hlIVS0kSllvfeTUV/6Xa4CrEbEcY9fFtqIFyYc0Ilu96VbCDMZwy",
	"Q5KVfadKhdKhsaRNd7tc64zMXJvbjf9UzHS0S+KK/3qMzjBoMwZjA9XhpAijRGkQFdosa89XecaZIzII",
	"qxsTu8GhTRXSQ3xhReXsOwVLGL9lzV5l0ayVP34jws0PWofF8ePF8isSqVr4H1wT/Fzjn0G5/RZlBa82",
	"CcwSVsSM7/QqjxFENRsGoU8uFG8I4gQvEtUF3+f1uKPdQONpWDypYi7G78eo6n0ZBkph8CpVNQXN9NHM",
	"4J1lVNxEQwEjYXvNpbG64AlWIe1eIVumFAcVaNQQTSZzVov2qQ8iWRZyxcuo9pek+etia5bAiemBkVN2",
	"eyVlprxXL4r6jwtlYSsDY4zEgmjoz+PWgjC17aE2/zSOoOSKAtSs7kma97W7b4a4gWIVGZ3JyrC9UZnA",
	"8Z6E75zQnM54xoHQPgx7lW7zGj+wS7hiRjP36iXcJjuWcMNox9hALuVcj+A58FawEzWCsv0YbW0W3NEZ",
	"Y4LYjsebRxKL07T47LEhXfhTnzKagoqOJkcMOAhXDRx3WhFbwtNpoXlZgAnpasmVo0CUmfDZdXxpnzy9",
	"x9LupdScu+g0is1lDse1IxTXOfhHc5qEqHrwXvPs2whatZI3jHSFS2RU6RMHmBfbm5dSoXASNsYjtY4L",
	"jIPlRvnnYRmQUmieEepa2QgKtcf6hCuWctrzuILNyJZIerfu+RL4KgOwuyssl9x1W7UiyLqkna8YOSN4",
	"fNoyCpwWVXIqubDFDZ1T2sdU5wW75bJUlpr5CiavWbZu1k9R144rmv8YnvjNJPzP4eR6R4d1zVfRTRVB",
	"MaMKkIMWukEXFuIPHpU5vsVStY3pfdmfLipHSY89tgBlTTdF9zQDsJG8MTUX6IPPDL+UCci/DSz9y135",
	"jipVzkTaZz9MQ+W4e3gyMyy4VRPWvt89jnV/13R3xnxmBhgX6tqHkPCrjTqwNRcfubqj17c+BGWKe5Le",
	"lW+/rTajt/YjywsVjFCgRu81+K3vyuym4zb3qkhZEaCknp0qFyhTq1w7K7Mbkkl5U+YefGBoWjK+EKiY",
	"W60AugB4Xacmu0C7CjmhgYidxgq25Bi3MSE2jcFaNtAuA9EeaHVC8DGuMHq8URWrp47Yo9lhrXBWP6vJ",
	"JlzeWEZgixDUtl29sBiKnXLJ7GYpqpgZm3KL2zQ0kgXCL8XCPcFchfYmuWte74h2d+vbBgbmO94w1W59",
	"u03Qd4IVo1uORVULWQFFoWhW/g41g8p4NfWfZFzcRO6OLOVaFl4DqFUs27vExdCN6Mdu9/yxJnhMMM36",
	"ODbszalzT8XynJ3naqOrqO39qznoHuJNq0ZQc6nltEC1NO5Pczgp93SSbZtsNzBLH3eBdwc+0GcQLPKG",
	"3Y37gy/YosxogS4aHxZkS1nM6ladXZy7p0xjENTKe3n35dh9QZXG8WIrC00AytHv0aeLcREJVXpkRjT5",
	"BsZjDvl/PcSBu9ln68xNHs8IBDl6O6cVyNF0GMZS2MeBx2w6tKBV/qEj9CmqCucZXd8VfLHU5OXJOZGl",
	"zkvt2uK/1MG05kOeWrK6NuO9xv7AMnpf//J9Fri3MxkIbY++ZFC1yMnpOZmevno5Vkx7WKzvOeZc3cvZ",
	"7LyjpnckBDn3Cfg+Adrd2moUAymidvRSMBgm6seggmueZTYmiRdEZpgg0c4B7vZw32uDPqo7+3fgyA3Y",
	"9Kml+tcXL7rS0CEg3OFibsZI22CpAytm0zYHmRmqSqncwFOf7HaPjIbMm89ZtywkM0OgwGgGuu6U5vPr",
	"KRpLdrApO7LvZVjenVz/N4zn38zYAh3tHgDsva58DYLowjxohVqgR8HdEVRFNRmfMycsm0VmVR4U1wl8",
	"tJDsZCF929BcjmpyjPhTnnGOyRRznqYkMwq75WGKpBY3h1t+aHcPQs6Ey/zlq4XL+0WH6pg85+AXvoNX",
	"ERsFML1sjpEiqdM7prZo3cgcuOmQTP9zFP4yQiOsOiJCKsHncyvPDE8ZQQYylKOWhR4T+x6yxIQCw3Vl",
	"LYZElcnSjPsfVy9fGCl2+dMPQ0IzJQmUp/HjuGRJWXC9Hp3LjCfrIyc3ps8IX1HIeKZlyuUQw12G5Pz0",
	"e+sow8Kgmr3Ttl415Nw5gYDavSI3jOXkThY31mfrvd3h5uF2dESTb9U5IliKcRjF3Zj/NnBFnV0i7FZM",
	"f3UU7si6XREW1Q5Ic8ZjYDWPIrvWOps+cxEidCZvI21W9B20qyeah9P9dhv6Xyt0IljpLUffA/c3E41C",
	"pk88DIAs1kOijZCmOS0gpmRqugeXXMpNFysuXIWqFc1zl5FSXf42WgGqS+IQxeTm5g5K1zKaNfprccYf",
	"+uLm1Pvq1bYaJmAH1dwHHZGoSWCNiPqmfZBx13WIu6L3Kl71vl7u3nRny9wrpsu8YQa1j7jRvKsxyKAQ",
	"u2CIKuEQR6rC+qp/lR1fpz8C5xvPpDmpvoiXO9NsTKa01HJKmIDai6TCNRv5hBhsbvnqMzJN0nxqszxU",
	"yzdtvSxSWN+I42allgPwdzfCdvD3FvO4Y7NCJ+cQmsaKbqhRTA9egfyrNia379XARyvYu5ibPo5G2szY",
	"xejwxuA2sIKXpe7I13qdpzSsjgXh9LkNMR/ZzKak03OFQfchrmqjhFpHYIHD2N0eUjBbV+NRKERRitmt",
	"D4f2aQIHVBXW0tMOutmT6NamoHfVtoRexR0WRxYerKizRNX+vYVxy+4mAj2Plg9DwNuRBQsOMf4DaLiG",
	"EkoRdfhhpunhYGXRizcibjiU4xYwpxmE7WPTpJ0Xupl6J0NPzCaQoUtryja6xZ1PVAb9DjgMqCZB0qCv",
	"Ag3JGfDGHiB/ps+mowrgx4FFWAuIR+2poa6MySuRrZ3Kby2GwpZocLgwEO5msV58oYyPDMHTjblzPwSE",
	"5sQBZrMCRHBoHdnaTx2DrG08AVeRJPT69tlr8qcEA9gDupC5lhgSstgtz8Cg1YXsAsUEGU3H5DkQUJVd",
	"5kG4pIuaidOjzcq1LFWwGJhQgMphT6MR5LCSQ6RgIQkijvthWuhn960AgBsSVaU/DebHO44hcTQ33fOV",
	"j/tAbAR3oKjS1cD+4oBIzPoogEuxdBOi9Cg/hL9ifJcfkLVDS+FQqptwS+Y3h4wUeHP3hXxkxMdCjsyP",
	"IwtyGHJHpI4Q1ejBOElh92HHe4crqswKHrFgRdUNS3fgARbWaANy0Tvzn12gi2qGJL+YjkkGh3eb5NoB",
	"7QMTNgsMyutmZmiu8Ovnls0hAsHabed3+1yfDjSGethQpzkt80nUENF89Ea8ESMyxbK3YjE9qsdIlblZ",
	"Ei7MEoDQfwYH/uT0vALQ8dc3KtQdK8ia6TF0aoPvgz7BhCdLyBupRZh5AMJaz9ihwt58HFDQH4zNxmbS",
	"LFv7DFD0KVRoqADcWTDAlgouB9CxDQ6ZHtWijnwUqqUBG8iJIc2tL2BPaP40PVVx4iyjubJ9hD6OhEJg",
	"UCbFghWm51K5bjA/3ozHbgGozBBKjY+eNWdmBoduDT9EO7+AJ7o9rmflu1Ud+KBcb8et5+oHtjD/dlc8",
	"/VUYcRS19vuYJHOsMK4HjIaEYeVwBcdyjSYBL8SaeQo4zir//40I8UrbFuJnLvvBxzhjjIo97orMC6aW",
	"RvSoKt3b+6feiIBA7CKA7MIWfimdTLUzVOTOSFdMJ4Yd2eDO2AWG4HWRXbFVnkWLkV/RWX2RnQ8845oV",
	"RpF47/JOPkwJ3MeWMksdcnQbveDsdPwQICFPEh4egc6w2jWGBZrDuwRkANks8GPLY2+79/a49qGXor16",
	"2z0XttLJJdPmCKnuqj9KmrsgtgIHMKAHQG1vX3SSOOMhsZUGuA3FXHERag2H7eiTPpkA9dojELYDIUcb",
	"bEWScJFkZeoSzFdS++ot3EYJO7BG9MM4c3gM/PdDfAl/4uwul4XuWLzA8m2hg27tC4ZkoCb6VuyglN3y",
	"hF0mNGPfA153LJDDNMEiHgRurUMjk+DgakkODw6fTKydHesbEArZlehIurUFEuGUHFrdwXwuJbZqIXpz",
	"DUdGo0diONjh119+89QWDqk7eFsVNYaDJeOLZSxOxC4LPjf7cnJ5Gev0709qpXzMt7cV83kQsAngT5tp",
	"j7f7Pu54GvPGuLnB48bUyL/Mj8oGiHw1maDjAqueaWl+qa/pk292nH9XQp4brt+TKHNwWY0Rii6VxSyy",
	"4topLuCihdQ4lOBjcuoyXqzyYfMU8Dg2008iVs0+mT0e/7xfTs/Trz5iTk8Lt/weKTxb8OJtbkpeyFtu",
	"TnvwPFKvAlExVRPDcn/A8BvCGM7LAlQhvuDgwMEcFiuZ0wZSfCPrr76KKh7tcPj1PTZ4P5lFjggbqUXx",
	"8LR/lCsqKn+L3oAev2N6I8ZZutHsJRD/O6qCQYFrOUgQwwxqp9OER7C2f37jAixVHOvYuh2NbE6/L+TK",
	"FY3YZ8LX3VKqgF+5NDbrNkqtl6hFeTaXSDBb1y7w8I33nHDRqoXxe8m46ET050F5kyB5omLZm6RKt5/s",
	"MqjHYG0VWPSPrOw7kVD5QFZt3AHXruU4CVL4O8fc03VS41EP8Zn4wX5sp4mn0w2Gv4icrBmmCgDCMpdS",
	"LGV/w9YjVDEdhY/JFV2M7goOdpPAu1Z9EjDloF4a5nzfOKwQ/KfNTKljnuyIdRKZP1bmdWp9e8fdE6hD",
	"yR1EwXYtfrEzmqe/U5oOv1DWMY/huvdA8gy14QiCdzXfTWTl12WDerkIsdN8xzFaQ57TCdFhSz3V9UhK",
	"CnbLCsw3AaUyZaAfdHCHPkqkRSf5VGnh1fC3qJE4zvsokRjJ9+MGfcRHMtvFaOsfz234HxMLLhgrOsxl",
	"fI/SqKZPxSRQOLFt0gf77Lio2w86aPQACibAfighiiPgVvHozPus9A51giy+n3sCvmgfHdcV/daxezsX",
	"FWpKk2C63Wv+0kOvtIuc185nz6xcX2GwlyjFMfhCgSsuXJbgzlUD++UhIpnsNKWqAl6fTzR5b6V/2X6C",
	"EnNh9mo1sD575U9KQ936iKvfVNTw092D76mkWXidB6poVnp9bAUtXNB4kU3ErDI3HVElFmOsvse1ioBZ",
	"7Q/AaEfAoo4ArQqDK1AalwwCtma1igTew2kNvilmwnAVQM226xzcv3ptL50CRv44KoXt8bt1Z9HMsPZl",
	"iCmO0fE2z8gPs6lx6KK0NmsoGIM2PZro/ZUJ9TNw699PX2hUDm2pDf55heoWnzHcnjcYqxoVlRHQpqWd",
	"+QAYXGfvNHYuvFpxw7jNqvf2x9S6/ahaDRppAPosWf2wbTBseWskVdZPietiWg8drsAd10suIF7DH0JU",
	"eixsW1UAOwDW4VvqLqM16aqram6jRq6WYHBcUCiFwlX7FFiU69KepeiBcETF9X7ORO/a0WEQsTfN9S4o",
	"/bstHF2wW3kT56oX7FYm8RtSlWlpmZ2yt6V7XJO6Sle/trbZaAVrL053q1f9EDW0YaLFEjRV4WoPyBll",
	"7tQz9HTFBVcazmw1jT1XSfblkcMCyNZwGFVS66KhLuyaB/0+FZTh3Z6KYlsF8RbsGlN8sCoJGtDH1iTt",
	"HkZ1mJG0SDWmEQGDixTk784+ZVFSXch/jVlvD3CdHG4tXjIcvBuZByP76cHR382I4QKzsWjsRYCf3Ce2",
	"+3u88UubX0IFmaYF5QLDMCkEik2DL04fqXjr5hKfUcOSGWZsARTTGN1gg6JdkIMN3yVyDvUnAUN2yVYE",
	"OhqTH9ldrWKiGY8r7YvRu8wndtZ23NZ+bpdL/m9ck7Vf3O5HKE+693jbXQk1NgY8x95R2RU7E5zkWD30",
	"wU611Q1516qpX5rDZwWjx1Ln+hlkSADWlfVecBdWazOf8WFnmXWf6xV41anepHlEl0hhItyDrWUph3iN",
	"7e/0MBy3OmcrGxDp+8Vftt9a+pnSuLoEZeUYsJarEQRMxoUvXzJd5l2hwucuNBySOG1sg7cWWPCOBdMj",
	"1PidgbeW0+icv1DZxUVkDuwaXHvBi0a4a7fsg+Egkwsuqh/i535Hk+F2Y3h96XYxBBrS6zD+NejhHjXp",
	"PcV0wK0KM/mM/2ZD5vCWA9ATiSbwck2x70FuTRKqfxg1xTAT9o6nLFSOESI0ZRAIC0Gdcu407ABUvCNo",
	"sMta3hxY90bc8i5v+SuB5OE8ZY66G6CoVd2mwBT18HjduNXuAtIpzTDwRkEgz865NYSyuf62bJGrp7sF",
	"w8VCpG0OaDWr5fT6B+jiwHg/tire7W92QYSK/8aG5PT8YtQIzTTKBTX6CWYWff303ddPR7MyuWFVNndC",
	"xS1Vtlhlh4Ma2/zDx2luq1FpWv/LBT5uaYxD7d03Nu/ZeY/w2OfzOUMPatoKlA2oLxatuvnbd32G2CCF",
	"RvRlY7rNxaqv9LC+S7HJt6kLMqER1uQSi7fCpQXur8e23i/+63t38N3FrroAtyBl2k189dlpreLsEbHl",
	"gxEvBppaxJhx9bKyjB/yXWjhAOtprq+nRlWr5WfbNzCO2aXEmsbqGmwcK6p9SVxI4nHuXKrgi7Rm3cX8",
	"Baxra5g3jLaiiqXWeSybvGvJVGSsrdW7qoGU2ZHXss/BbGNuozRn11OCWJEN+EwPhrEOytF75QXdQAqq",
	"eh+7FQBZMFuTaZiNMLWV5DHkhOoQMmHrutyxWWfFCUStGAEuWyOpnDAooQNV3syAXp2dngwhF+2GrWHy",
	"Pp0P9ACwsJk+EylvuDciASYoLPx1q+YKzfk/2XrwwZwALuYyIqyeX14BRcxlQVZU0IXR9/1WWj/hsJUQ",
	"P6zivIYBDQ9DQza7hZSfN+KN+B//g9QdCuZHvH70PSpADUGZCFfCuw0A2VxYKqoRDjcs89h9PExI0vQG",
	"8NAT81PCUIuAIvLmbNnUSnTLLRnN9BKDhc2VCWr4Ja2SLdZOHavYEjCDFV03I8GMbpDo6lhVtYOi9vCz",
	"UzUmRhmxPWJkRKgRSasP2QpPhYWDdzt25WpAZWgQMT+3B2qNJLwgs8AMOyaXERsrRq9VupqF/QNOtyoz",
	"zfOM1crU4Lcrey7yxP8cOQId4XhGZ6n129UwpIMwFRJwJ9MlRnfCKlTfq/urrAtE+PECxLpgbnnO0Uhq",
	"F+YFV9pVBYbgujkvlKtKODVqz1iwdzbhCDOlE/s3GvCxzZKql7KwLgtdlAxAKRcWTTCsMP7VBMtSKMME",
	"zWypJoeTiRvd86KQhTL/wL/QZvGevBkw8+83gyNi/pHIlJm/3wzG4/GbwZC8GayYUnQR/ko+kA/TMXlO",
	"k2XAXM21ECyhCnOPpbIhaVgYzPSsnpEpfP7EuWEcfg0UQUuopplcYMl8pjSZyZTbGJ6Mr7j1MRySl/w7",
	"hyNPRTCEVCYllpmlJDNaXYHvoUDTXIM5IhTUg+HA21MHk/FkPAF8p5wJmvPB0eDL8eF4AlZ2vQQt4YDm",
	"/ACI+ICWKdcj5GoY0AgKkh/OWQr1jJU+Ng2fYzsw2NMV0wC31OFTqJocvDDj74SPChoiJUFLkAq/lgzQ",
	"rqxQCPHcQTfvH1oT7xCUK+uR6Ndjw1e9sePGQFu3oc5XbQ2yXd9slIW79/tbxv0WHDKQjQok82QygZsG",
	"arhg4swNDwf6OfjFVsjut7wVlcGdD4R804efciuGSQ5thhVaYrxzP9oDOLeoO5erFQXENUPcxKnSgAPo",
	"pPzAZQP8PICfjRb+buQ0kxG1WnbNDaaqUmLX1JkA3EXh0noiG8XG3jo/4AVTMivtRIXU13YhZ2g9D74N",
	"/A56skVOuBTXLgPazC844lbfCU53y4TqebuTSRlX6P9u8YEr29vH4AFbWp7aLPAeTdHufYamQf/eY1Jy",
	"ELoWoWKrcuyPgLXfFkey7pfPhWiHg1yqWKYyWLdUQ1+igc8yWq6zTrnYiY3tw7kxpb+T6bp7zV0TztRB",
	"7f0PLbI53DPZxEjmxEU7+UE8iGpOHNy3dovyORCOLep0bXfnemZ2cNifCR68dzrEB6Q0wwlimdc2ej+k",
	"O8wmv5U3VjkMwzHUmJylbJVLbfP/6+SHHCcgv0dlOjHqqWa0NwqquvzcqKhNLq63a9MDFHtBjrSTiLty",
	"6qkRLDnVybLT/YmXBgfFDFUN5DyaE1InJPRC3p+P1d7/8Eko0TlS90SF2N0flo9FCNP/lFZnuge/Owhs",
	"EBtves2Mgd11vdpBeBCJ7RCyH6SjtKsldSlg4ZrsUQ+r9VtRZKnMAv4e6THC/Xahp4P3mKLSEKrdQjDY",
	"rBaFPO3M4wqsWqnX/R8qxMBqQ9sb91nsWzXcPUmu7Vep15iMBDKujLCQ17lihY5u887CKtrT44ut8GM9",
	"WMe+dHFZuFzEz5Uc9y7WbNhN2Koeh9ODTxUM4rwggCB6w7zABpWqPyYXGLXu/AGIx2e1/7StltkevF72",
	"qcTl/TQyO/q9qWS2vz/oraBBb0AgPW1rjbS3hh+rnuwWt75BVNEVfvNjWOCauSo0cdOo0nxcgbmoMbuR",
	"ItDXClxLzesaSOibI2encfecW+ElvQXM4Kp5x5Af5GRomGyoYiMuPNQfUeXMRp8i0HdK6IJyoXSQ6tJO",
	"0a8lScWG7BMvNhj8W3Xiy0K4tQlqQEHiFCKJoxu345PwsPcS2fyYHrRnGe/3PNOseGSG6FNGYkIe9mJ/",
	"9tnKuRxyQ/zhD2OhFY2j553XLm8WswTBX0qzjBVfBOmCFti5ZlWDiAEMCHLOKeJz3sbkmCRLKD/rSuyt",
	"EQc/53DGAIwW3xq5SINa+o/F9rfIhwg2XTChv1A2N3Ros8OGYV822KFKW/YpakEkQsK6jNAVC7+/ITro",
	"4zGN0dbqbb7jayRvsky7Ae3FMC1qYWqfwZHZXfn1UShhnHlfxRhW4tqw4+tEinnGIRsFf7V5sKZnJG7W",
	"pbkcvNeYdWf0ZMN6N6nJaPsOd2az2RvfqBH8jpqxzQiMyIGYlQDOoVXS96DFmn4+QzqMEhwSS6cai1fK",
	"TVbB19Di4+ucO+hQdXN6UeUVxBQY988dlKZLG7iFJnpYsiFxN1H8N8ESMrKAcLqubwdZJNXng5KP8IEw",
	"ScX9ELxIs1iu2aMqTD4UP2bVV6zYo7pUWmr7/Zs8NitKMQUAUhHuLfpdIsOjCX38QLeUL5WL0N+H97nE",
	"xfhDmbbAQoX5Y14yRxluP7M5nnlPNY94uKOO45C/Pdzcjr19ThvfMECa0x0Vkj8w/an26PU+tuYHpj/z",
	"bdlNNQn9GM5XH3O235ddB29/+BQ0Yd3sezm23sn+h2XXLQ/DTvz7gNfyObcFsmEmJZoUANVB3DQwQSFh",
	"2Rf2M0MhNE0LptSY+BASKtZEllppKgBkskqt4eJms3kCEiUSFpSmURaTWbFbJkhK16rLgNHIX33AuXtU",
	"HSYY4gZtprZme7Zg4C7WvvA5slZ7ICoSvw4w07cdjL5BJ2bHHhJy0k1Vf/CAE6SyL9TnGnnSkuMbySni",
	"y416Yq3Q/jQ0dB9x7X2we5HXlQf289XnPB2UenmAwBRRF+tVHckLJJrPDNeNdL8xOY4DpfkSFiLMQLRv",
	"QeEvfmujNtGZuyVQ8weow1UwoX3G0M70eGmLiXyc+IDjUi9fxu37tqZ27meyj7uGWcow9zUN+g8Tb/Ty",
	"fvTqiDFKuHFSdXVur5eMpngM9xEpYFN5D5IlFYJl3dEC39mcX9ewhljua8zZ7NZ4gIDt4sR96hEJpvmp",
	"COU0J7Qnkedrcc6a/VeEYx89Au00kJUfxPXsKK/dBDpUq1Z+5vYMLpuoTo6jPlBtXSWWrcGFAN+Ai4gD",
	"w/TZzGEStnpG5uCeBx9rkpSFIjM2N/Im9+nD4wqu1CyxgxPzGYYIxAeBBiOw49s+VZys75l42uagw48W",
	"JuPdxQ60eEhUmSwhS9ohNDRKQXmog4dmd24cTwAcHTjkG5WrdgV/hOrmv9Ok0o35pM/3nElaO34BP7I/",
	"fCJ2hP4/K6Nk4f3N95F0MJNrxYpbnrAOhoWwEZ0M6wUgLueFBNQHizGBRYBKNloUjIkAuwuB3YY2NA6w",
	"+4RVvxKZyRjP+IHpf+AQHpGu7BciRHWJi2NnVgPrQeWjrgqpevOKaJAKOogGoThcTQW38o4a+gkL13oX",
	"OdEUDv3EwUlYELkIYPosjhnPmkW2V6XSZMaItqYaqkJc3raMuHQz/x2kJjczjTt4sorWOi9VZ9QdAiH2",
	"DrurVVrvE353RRcArtOr5U80K1nPtg5F/nHvMK7Cfgevd4BT++P2TQih8Oy6n/4ALN9+r4Pp7+VeG7eZ",
	"X2paABKKW2ib/N0s+zg0Oowg7gKXrQlf5dK86ndIy4IumM3iDZIwXel6QxTYPRfc8Cn/KmLrqTE5gz6h",
	"lj12Zr+OHc3Coppjcsk0md5Rrr+XxQWj6frfAFF5ijWIgaHWyuwD8I1WNaAmq5tNXUH8qcU4tWXc7cjN",
	"0eGiZFu4OJbep4U2ywnF9tynffVox9obU7myeNFBUXkAYEttJWoz7HZ85pDMSu3KAqPjwXXgxMqKckBb",
	"guqb5HsgNz8tM96M0VuM/gQ4GyMapkiV0xDOLOamuPTadIM6G4XFKUd8/YpQ8PNw5YHVRqMjovNYyYYz",
	"4mIxJqcBfpERxV28OySFeOAPAja30Ebf3jtWxC3B48eI2i9dMGVmssHf4jaNnGllhR3AQlUUjrUuYgfH",
	"7gjsDqA38ywzRyQvJEDBj/fnuWnw9Udh64kUDgrNc/b31a+VbVsWYFAQ1wBRXUF8mhGbk+oQty0CLZ5D",
	"uHpVVOPqYBglol736cNmCeNrP+1RxOzgnHVs5RoR4q5TJjg8MBO/dlOpeavqT1yi6GYhNhxYVn69kqXQ",
	"1fedgQborv2zFRUW6a8NPuGW8WBWZjegtD+WpMSMDkUAopccTiaV8QYy1xCMDOo/jMlLrhQXi6FhfIwv",
	"xNDl0yLWYSnaBqCCEWkLF3seqIDvhRh80ZuYU8y/M2twD2Zm34fXPzy+9mi+sync/bumzrcPa3hTkSSz",
	"NTk7/QOokzuc9c1aZutIvVeuqvhGLJdLLXM0YK5ocaNqOtfUkv3URks0i4k7DSVQP0qheUamHrR62oX2",
	"Uukfj02wvvB2FPfFluCvVIH95Mt/DAn5kcXSTvLHEWsoedxvSBwPljmGRgqZhXHFUYuOu9bWfKCJddqF",
	"1wkE/6zK3Xfz6o9AtT1Y655iGj8xqX6kO/ojUup9rviWNfcxD0W0nE3M/qAGlz3ycNlGVXhfyIx9OADU",
	"342pTNYAIAUj5hWHrquWFOyYttiCiwqwQoy66kq2sJR501ye5Z2oIyxHUqFgRCfhyE88zvfgYcsLt82c",
	"guXYeV1kxgYhQj3eLasD6lJLEIHclnRnRSylZPg7C1ToIfUuA5sK0kLaCbL+8GAb+ACh3V/4UzZWvzl9",
	"0FVP2pUTbeYMaKDvcn24O9LdktnCcAzKr+sgkgB6AARqs/8K8Jq5sFUhof6aLZ2FhsREFikXCwcSXysA",
	"YKmKrCQQxFwWFWJ3LrnQrCALpsy/1SZhbN0OH5sHP+IRxhldYrk6FY+Hg22x26F8yz0oBEW86z+1gg1n",
	"0bQqSiGwCtNmrXaD+hqtCPccLlbKCFKb31gdPidvO05p33OpmFYPOZy2qtwtBzT46ZBM8bVpleoJF0jb",
	"WUaVVvamGF43lb+K+trmGPXZPv2Xv4fTv7OdRjcP9iflIS4FpngcXnL5u+Elv1cb7SfgMRvVgznPXEnJ",
	"Ltxf8zteC9yhNS9h2R5b01UWazJjmbyrnW3omxRSAi5J1RI8ikzogjPwdFiLkw17gNIfBTP0w2/Zv9ni",
	"GNNU3olM0lQZVlMxM/OvMncPIKJOljovtZo6LJMZc18Yk2Ox1ku4zYCnZMbM34ZWNBNVMBoVhIuR86EQ",
	"9+khwS9Z6BM7hCHmEf0C3GKL5et7Dlv1UdnWsF0iUi/JvJArQsk0GNhzoYv11Nqw68FufvEPuLiVPGHj",
	"PJ13RrdlVPNbdk5tqFHXfateU3FryJ43s1WEpOUCtVakqFtW2N1FWsR69fExWvKKex076vz2g9xomBfh",
	"FKAgt8Pen8Gx+xN/Xq82sVWzXtGm8GBWqnXwm19UeMP5G9tP80JqOHo9LEfxCEAoLYTpFBlDpch1bzjl",
	"JgYbRgI6jdAf2mFN+bPcEpnleUbXdwVfLDV5eXJOkHWOyWnwWQhKtswayqYxDuadIVHSVgiWwrTLc0YL",
	"oqV8RmYlz1JCiS4YQ1YzDdnCdEz+JYsbZTM815WXwc5sSKzUM1QtzPRQc+TapWaicplxpd3FFM5EQavy",
	"5r66/cbYuO9BAH5mF8leKXlN1t4nJe8ypKx91ZEJu/zzSnkfQ3NHIBggtGKBOSyrRgtN4L+guOESas+a",
	"dQf4Hy7I1LOr6RZ24oJPLCi/V92WTBAB6Fm7nuEx+ZGuLD9RVHDNf3POdUqgxhhPiCrnc/7OHGmMpAoq",
	"+ctbVhg5Y3qElDSu4G8zaozyQhXMO/Ytgq0wmqucQ0QWzBBKpx3bWvcoO1d0TQLYO5eMcI288npF31nR",
	"sNYM9MwsC2+wEPjW1Yd9fv1rKTWtevDDNO8ltCjWhJqrt4LybjjSYU3bMQ2XMkvDdlXDuqkt2Mta80lc",
	"tozJsW30pZMPJA8qLTo7goYU+WdkJQtGDPVbdb2xXokU6GtL1h5szfuTfQk4nNGMGY0bqrqZP/RSKlsV",
	"TmHcHBZ5a8JQmO98Sg7eVk97XYSIlkiXgZznjbL6dgOcqq06EbMqZS8GmWW7GXQAYu0M3dFa8Y4Qus1i",
	"AvthrZ4eiMVhOv20kuaPYXCImxZq6rGW8hqOa/hajcd5fMXGm3CqY083sI1urb2PYeMg4HF9UEj6WTOG",
	"DoZkTVYYNWZBUhUG7Lqogva9jNDMaCRrlF7KMFTziZwiMN6GmN3T4LT/7q2eHSN/zJjb9se6A273dxP3",
	"wbGOSP5QN/CPz37giOPZ6M087uETtbzB3o9HZZH1gijiC6Pevr54ATovxEk0dF6njIq1eQpcwpxv80pC",
	"hb+Re+HfvtZu5gJGXJ7aTl5fvPjseEFz/B8hdLX1ycilFze2Zk2zo9svd4CePRHgBv43DGZ9oJHu3gd+",
	"JW83BEC9lLcPdXMMjXpPBUZCGaEetG5cq+uKQ/0udqatJ7SoYM2q+y4T2igSInX+DTOt2hDBB8y1Ytn8",
	"oY4T0/cWt8lm94dZ1U/o/LgPx2oO+SMxKWuja7MnM57HdCeY/tGjBWaiP7hb4RMpNX29DRs0INPFSt42",
	"7mSbHRB7V53yQq7kpjjSc2ygwoxUn1Mw9KmKwFenqlQ5E2mYuki8/8ymKwF2uUupKRVLiSv+ktAsW4/J",
	"dC6LxDqKayzTAiL4jrw+ZveepVhZhlywUvnqGOZ9sDEiaLqlK6xvCzlAoP115pSqZ/YTqsyAX/vPN1NE",
	"fX2bL1RQwaPFQe2CduZu/v4YaGPEj8o/7eJuinz1eZa27YMZpp1fO4wexH/1nYBbuvzCj8Auh0E24x8n",
	"Cgb5juV9+A/zKCjzUSU+Nup/VK3vx+/erRFaRG8pXeyIgGHUCLxJzDj4oiws5MfVkgEy14IRIHoGOdKC",
	"3ZmGAqH11LNK2Qt+JTeM5db9WshSm8tjZj40TQvKxRSRcxUG/ulSCJZZuz0E6wFKCHBRIIoRBNv8v///",
	"/8s1NSRYxeD59HSjGOJMzCXWAbeCx5WRGU1uyIqqaAFADDVz8BOwjJ8B78JR43A/fNqIfRert6/MH0us",
	"LaYVIdQ/Fb1PHLVf3dO6AaPAgpzJhdGDgggPn6HD3uUS1JqlVBpvqQjzaW6mmwGDLqrPf4xIBf+5XUIU",
	"giXaa5xCEc79DxlF9Wni3D8y598CnqPprNppCC8Acy5N10TLfJSxW5ZZlBsoqidTloCUh8NkDSRFWbN+",
	"VLGr2O01vBUu0XSLfbc6CA+1tNaO1KN5XYKvRA6qWWsWZB48PLzcQvW0jup/M3n1kANcUWdTgG2g20cK",
	"Pq9Y7cF7/7fFLtiYrWYOa0vyVXBRNs+7eZDvLRmrvLPwgD4iR7uoFuP3l6m2+dC3juZ+Etb/kEf+8c52",
	"X7/Jvk/uQcHwrG3zs1AfHViXxIEDJS6NLdBbbm67xS0gnwLUmuvg7HRINF+xjAvmM90gBQlT1twbnklg",
	"r1wRXpXtJD9B6vcQ0tNyF6aISxOq2s7KEKvziR1/jnxjR72jc6ofPhUTciPaq/LhOv1T/3gEHtWtlXxU",
	"7mWOezfnQtikGjJ4xXecbqELKtScFYVjNCuWcko8CE1hVZiGk6DmcvaOCvAhY9JF9akvlGdwGG/SzpTV",
	"Mv9TYWnzCnTnRjwENn0k3M+5df0+8MIi8z+Vl8+JMciciU0gOcoZENrOTfBoNpBYa0d+XjC13IKJAwP4",
	"lL6+T2fvxrnv1eBtOvwTmG3jsYRD6LH8ggceiQ0jlR4dy60DWHTLibV/jmAd+4NcQaUlWCULvCznhJKp",
	"5Ub14+uRrux7MrOu/i5IK0vr96vv/3mf4RBlSrC7PVWP9HBSbX87LvGfx/mjeKVsmsdIbTtlKO88vvyG",
	"kl1f+GaXsMdzzrLU3NQNYWMxJPKPq6tzIgu+4EIN3wj8y+jGmpnPGNqmHGwJfyN/uVvyZEmgfhJT5DdW",
	"SCOXIWEtWdKCJubg/HVIfn4z+NubwVsI5sEUSsSdeSOCz0GU0htzyMVI05l6M4D2wAVwPOggp4Xm6KSX",
	"c29ZyOnCZtrNzYFV4zfi3I0Z6zuZfnzqsvtilcgN5w7h+YUUIwfPk8tCP0NTJfjzIagoy+QdS8dvxImU",
	"Ny5tG4uQ4MKnckVN91B0hZF5RhfOPGLvMn4Wz+yCwO2DK1+XZPxGfF9mGZhPC+1+huAlktjPwtWlYGCe",
	"ERCvgdvnOyc3bG2W4iSTysh6ru1gU64SIzFYSvSykOViSU6WhVzxcmWIhGs28pcoyDMyjJkJGzT7Rlyx",
	"VS4LWqwJVzKzlWzNDhSMVuUJ3DVtznSydPmtfglgNBClsYYxJThIKAP8RuC8x+QYYyzcMtiwLkGoliue",
	"+PifI/t9SPDEmA+YQFoWGNqRuQqMb8R5Ic2FY3THU1YrsvgLS7SqVo+luJxmoNjbHSRMVlYySzTooXoj",
	"ZnhxxHWFTPxgUd0Crp8RT+KQqGCnBjF0hvfw9j6O34gf6Soo/DArkxum1ZDInP5asuBQIJ3d0qy0EhQL",
	"UZijtKKVM80RDdjZ3gigJJdYhgO6LoUqcyw4MbQzXzGlzOcxShAvylRJYXhIPUF3xjIpFkbgvxEWpPwK",
	"y1h4/CmpqyI8S1YwQ1Z4TwfpZNpAMCUG8H39lLzk3/nU29qsvlCQxhtyicPJcDKZuJMSS2t9DrP0JWoq",
	"tvjpI2f2U3Wsa35nIi9tjYQ6XsxjmhDPkAYswG5tuSOazbksdK3AoiWrwXCAsh3Gd0KTJRudoGbblozH",
	"2R1dGzobgbAZb6z/9uGhahMud6vci4X+cfb3Pw4E8O8bn6ubld3bXGHDp7dZLCMXm6G1X2BYs68YhNYK",
	"CCMsmDlh0WIyl/jZ/55WiksXsr43M4Xt8U87xSNebHYHlt948HBbtgUFhygh5g2LmWn0K4BNWlEoTJJk",
	"gJu0ZKuYPRD6chYFulCfQxCtHTUM979JEK2mf2Jc7hP0aMvxA7X94D3+AT8ty9VMUJ5tjR2i5N/Pn/9A",
	"/Asu+C8MNJgNScZv6sXo/Atj8hyuxxi4IIzqR7gwgvSNkHfCA/VCCX2RyjtASpvR5GZRmNUgcM2C6yXN",
	"zfKnNmZfSqjF3xQwUAsV7zZvBLzLNVnSFFEmuK7eeAZjOjtV7r4JLaAQnyXXwjowYrePKsoJr0VXfkkf",
	"xnLq23DVjOc4O0WNtAIt9oDEtoXLi4qA+jsC2Ag0aS1Fg6PB//n5ePRfdPTbZPTt9ejt+8Ph4ZNvPvzP",
	"wccC+OcrumAHv+RsUedxeGUcHA1mXFBMs2zeBZp87YrOKoqs30FeUKVHL2XK5+Y4tgENkOjAh/zIFxAM",
	"3dKNoX7u14xHuTv4BXr00K1dOeXQA4h9/XRCcv6OZYrc8ZQNXWSC2WBoULCECZ2tiVoaRgjZcOZIj7zV",
	"N+NMaLDhupdthX46s9hy0jYC9Dqb/sTSMbmoX1eVY56GAZpvPCMFyyHR742wwkv5Yu53kiiWSJEqKGfC",
	"gOHbDsakpdIrZLk4Obdciih6y5DrvhF6ydYV4x36XKyq+XXOCsWVvjb7hw2ngHaMgO5pHQ8N067u6I1j",
	"9D4f9rViZFo701MbaH429z+NLrlIsJAqvZU8rYehUEFKgSIhJcCEtvD/PXH+3zcLvWwK9t83G1WR4f7J",
	"Sj8aK/UZvP2KyLvm96oi717uV0b+ii5IXrDU3KGYgrLFLjb++MfTjjwvP52PURm+YQS9PDk7IwlVbMSF",
	"YkJxTNMvZ3hkrPMuJXRBuVAIkVZDA6jjJSIu0wgIOQaUKGwN2M4Dun0uYdH6bevDFjRZR4rd/8HLzNv9",
	"6awz7/Zvf4XmVUDDHyfRvl4l+COE07mU9kcrMt9ibwfvzXHZXD1UzvUotWUhaFAT/bnLWq+VyC0Fnc/h",
	"u8/CiunK+f0Mv+J6TM6q8PuuIgoVsMInBZRoIpTsEdD/Y0NHPCpSxG5Go1jd6n0fgLAq+L0TS4102lQ/",
	"sUCLbi1I1Iuv4KVOyISQzO8FX3AZEOYnPSne+rqvk4IdRpfzj3Fm9mJ/vcdR6hIEZj+0LDZEe50gsQdb",
	"kjHtYgBBV19DmWlWROOdofeA5D/Bif6kR8SuwB7PiO3xT3HSfQbMjzZs/wFHo78X0LQk5ki0JcIDnIK2",
	"h/t5BfdzcH6vjsFPIZuca9BzwqZP8E+pdF+pZGfeZXpBoiQz9K4hsp5ZTSY0GEVSgh10he3/wDR28Zg3",
	"C/uFqCHShp/aae7DXlgLa9Vuco4U8Yf+hLiJ8vBZb7LrpDFLlSF12J9SBkiOZiOt0r9ZAweHJ9ICdPAF",
	"GN3zjK699SgOVRayuPtr31d+np+AlhxX2xMpWX3786OmHThWP8Lr5GxNLnWAMKDdzAosvyumKcRvu3yC",
	"hGYZK75QdnnH5ILa9Bkb5Q8OIh+KH7XqIllc4fc/vmH3ZDeTLprA2/bcO2kuCw8w5sa8mW4pg2QRveTK",
	"ZpgoQ39dxSLhYe2bG1UPaP2hV870rbxh6fdg4n/ciwiQRJdpFglyf3ZZu9KOsDfwDSTU3xPb6MUfukuy",
	"VcUikLhrGknrhJ8seZYi7SkXegscBj1B3kJqK4rV+vDL4yqoJdBZYrFuZ2vEjM85HL/j8zM7ItulLDXE",
	"2nBMLgHME3BHO6aDuGYWBFSKhHUhlwU85/6gZWEnj4lXZr9mvnNhv7EJMXg/2Yu+DAQu7Gd5Lh5BnOJ3",
	"m2C9+Ku5my+wXw9b3iFnD97D/2L2vmGom/ISzXM4ndDDSN4Jt8tj8tJWZICEPVkwvhAQSjeTkNEGQsQc",
	"HZjUZncFfqh+MnYTxlc4p0G/ksNX1pkM8mQP91jTD0Qc1Ci0lW37ufJvT3uNWmLRcCkbGXBwy9ldLgu9",
	"ERyC/2ZLiLRQqwxV3VHDbrHkTxiUaZ4hSkzOc8R1MSxuDW6xE1cUTRMf1uRZCF0x94FE0oyphGFZXghQ",
	"Nd+DmE8bZIDhVoJmFns6JW5SkRwPHwz0k5v4HyMH7ZJpN6Mg66wZXOn3rCoV4GIqwjX7eMlqOCS/F5FB",
	"Hzf2dCc+8IL7micBS2BJaU4wbPaM0YIVx3C6f35rdvSOzVwKkP1FhcAH5re3Dbs0/w3lYP1wBCwljBb8",
	"OLHz9peTCpUlaHftWB5LuZbFdUJzOuOZWZPffSDUBp7mSoNuyhvbqbQwljly9YQOpoSLdomkIblbsoKR",
	"qQu2guIk+A7UHCI5T24I16TMH7dY8CtboKmwiPh8IWQB+e0PKwxM/nI4mUBO8GxN7Nn768OrBZO/HJIf",
	"Wp32KyDsazz9fsoH+/R+uIBDKYN2ReGnT76d7l7VeXr+6vKKbKkDNiWpdCUbDPF2FbBGahPrqv5Rdyni",
	"gH9+uoLyn2tJ348hfGyJYFdxGULTuzOgf59i6HMQOTvvHMy9uHXHBGpxDg6Aou1utCptszyT6xXkCDCa",
	"QSXe1Gym5itGOKyfXo8DAx5sTMRgeSYwbBwO+wzQG5csAGiz1U+4SHhOMwLFp7y9tq6UB58DCml/7DuX",
	"gmUH6nUJQGtxTi/oPwyTCzq2cjOWVIUXNCA9rnRBfQCGvbopls1H1sdGPAMLO3dG/IhZF+wXQyNec5Zo",
	"lyUOl0SLmx18WBbErBB+1tudal/Ca2P7Q6/hMpQkshQWk8N2s2KrGSvUkudhP6UyRNPu5tLS36gyRDui",
	"QJbeWKVE89s6wdAytabw2ErgfY0KI8Y91IxDVQliH1Gk8iIQLJpqFhKmC9uPWa1LVYObCFDKva/Xm/sg",
	"ga4pv8K1qnzPXcQzAjtkSmDuMPiMz1myTjJm9EChw+7wh1gVfKrpKM+oYCjYbSYNGCQBm6XOcm2VSlJQ",
	"0Mj0kgrX8vj8zALxgPKGEfKI/RwqKlxV4AbPCABH33EFbcxuqztWkOnTydOpR/6hZCbT9ZgcW5ZIkiVL",
	"brxF9TekChtnP5fFHQX8SbhX19sYdaUsbMi9HTMBBkuYuGWZzNnQDtk35ULxtD4F8/b0PXkzgFffDI7I",
	"m8GbcjL5MrHYNvAP9mZAPkzH5DtmOlDwrQBKcmhnDFBbYfdf/H8qhjcuwVVjAihuYU3xxDxEYaBQnFhZ",
	"rFCcrwNuMIP7O+AzihKT8qEKEL0fSEMImhhQKsva2FpAAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
