/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91Char93UsersIndexRouteImport } from './routes/[-]/users/index'
import { Route as Char91Char93TokensIndexRouteImport } from './routes/[-]/tokens/index'
import { Route as Char91Char93TenantsIndexRouteImport } from './routes/[-]/tenants/index'
import { Route as Char91Char93SnapshotsIndexRouteImport } from './routes/[-]/snapshots/index'
import { Route as Char91Char93SessionsIndexRouteImport } from './routes/[-]/sessions/index'
import { Route as Char91Char93SessionsSessionIdRouteImport } from './routes/[-]/sessions/$sessionId'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93UsersIndexRoute = Char91Char93UsersIndexRouteImport.update({
  id: '/-/users/',
  path: '/-/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93TokensIndexRoute = Char91Char93TokensIndexRouteImport.update({
  id: '/-/tokens/',
  path: '/-/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93TenantsIndexRoute =
  Char91Char93TenantsIndexRouteImport.update({
    id: '/-/tenants/',
    path: '/-/tenants/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91Char93SnapshotsIndexRoute =
  Char91Char93SnapshotsIndexRouteImport.update({
    id: '/-/snapshots/',
    path: '/-/snapshots/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91Char93SessionsIndexRoute =
  Char91Char93SessionsIndexRouteImport.update({
    id: '/-/sessions/',
    path: '/-/sessions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91Char93SessionsSessionIdRoute =
  Char91Char93SessionsSessionIdRouteImport.update({
    id: '/-/sessions/$sessionId',
    path: '/-/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/share': typeof ShareRoute
  '/-/sessions/$sessionId': typeof Char91Char93SessionsSessionIdRoute
  '/-/sessions/': typeof Char91Char93SessionsIndexRoute
  '/-/snapshots/': typeof Char91Char93SnapshotsIndexRoute
  '/-/tenants/': typeof Char91Char93TenantsIndexRoute
  '/-/tokens/': typeof Char91Char93TokensIndexRoute
  '/-/users/': typeof Char91Char93UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/share': typeof ShareRoute
  '/-/sessions/$sessionId': typeof Char91Char93SessionsSessionIdRoute
  '/-/sessions': typeof Char91Char93SessionsIndexRoute
  '/-/snapshots': typeof Char91Char93SnapshotsIndexRoute
  '/-/tenants': typeof Char91Char93TenantsIndexRoute
  '/-/tokens': typeof Char91Char93TokensIndexRoute
  '/-/users': typeof Char91Char93UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/share': typeof ShareRoute
  '/-/sessions/$sessionId': typeof Char91Char93SessionsSessionIdRoute
  '/-/sessions/': typeof Char91Char93SessionsIndexRoute
  '/-/snapshots/': typeof Char91Char93SnapshotsIndexRoute
  '/-/tenants/': typeof Char91Char93TenantsIndexRoute
  '/-/tokens/': typeof Char91Char93TokensIndexRoute
  '/-/users/': typeof Char91Char93UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/share'
    | '/-/sessions/$sessionId'
    | '/-/sessions/'
    | '/-/snapshots/'
    | '/-/tenants/'
    | '/-/tokens/'
    | '/-/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/share'
    | '/-/sessions/$sessionId'
    | '/-/sessions'
    | '/-/snapshots'
    | '/-/tenants'
    | '/-/tokens'
    | '/-/users'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/share'
    | '/-/sessions/$sessionId'
    | '/-/sessions/'
    | '/-/snapshots/'
    | '/-/tenants/'
    | '/-/tokens/'
    | '/-/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  ShareRoute: typeof ShareRoute
  Char91Char93SessionsSessionIdRoute: typeof Char91Char93SessionsSessionIdRoute
  Char91Char93SessionsIndexRoute: typeof Char91Char93SessionsIndexRoute
  Char91Char93SnapshotsIndexRoute: typeof Char91Char93SnapshotsIndexRoute
  Char91Char93TenantsIndexRoute: typeof Char91Char93TenantsIndexRoute
  Char91Char93TokensIndexRoute: typeof Char91Char93TokensIndexRoute
  Char91Char93UsersIndexRoute: typeof Char91Char93UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/users/': {
      id: '/-/users/'
      path: '/-/users'
      fullPath: '/-/users/'
      preLoaderRoute: typeof Char91Char93UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/tokens/': {
      id: '/-/tokens/'
      path: '/-/tokens'
      fullPath: '/-/tokens/'
      preLoaderRoute: typeof Char91Char93TokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/tenants/': {
      id: '/-/tenants/'
      path: '/-/tenants'
      fullPath: '/-/tenants/'
      preLoaderRoute: typeof Char91Char93TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/snapshots/': {
      id: '/-/snapshots/'
      path: '/-/snapshots'
      fullPath: '/-/snapshots/'
      preLoaderRoute: typeof Char91Char93SnapshotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/sessions/': {
      id: '/-/sessions/'
      path: '/-/sessions'
      fullPath: '/-/sessions/'
      preLoaderRoute: typeof Char91Char93SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/sessions/$sessionId': {
      id: '/-/sessions/$sessionId'
      path: '/-/sessions/$sessionId'
      fullPath: '/-/sessions/$sessionId'
      preLoaderRoute: typeof Char91Char93SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  ShareRoute: ShareRoute,
  Char91Char93SessionsSessionIdRoute: Char91Char93SessionsSessionIdRoute,
  Char91Char93SessionsIndexRoute: Char91Char93SessionsIndexRoute,
  Char91Char93SnapshotsIndexRoute: Char91Char93SnapshotsIndexRoute,
  Char91Char93TenantsIndexRoute: Char91Char93TenantsIndexRoute,
  Char91Char93TokensIndexRoute: Char91Char93TokensIndexRoute,
  Char91Char93UsersIndexRoute: Char91Char93UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
