name: labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: sync labels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
