name: remove build label

on:
  workflow_call:
    inputs:
      app-id:
        required: true
        type: string
      label:
        required: true
        type: string
      pull-request-number:
        required: true
        type: number
    secrets:
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  remove:
    name: remove ${{ inputs.label }}
    runs-on: ubuntu-24.04
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Remove build label
        uses: actions/github-script@v9.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await github.rest.issues.removeLabel({
              ...context.repo,
              issue_number: ${{ inputs.pull-request-number }},
              name: '${{ inputs.label }}',
            })
